services:
  backend:
    build:
      context: ../../
      dockerfile: ./software/tracksight/backend/Dockerfile
    ports:
      - "5000:5000"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    #   start_interval: 5s
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
      # condition: service_healthy