name: tracksight
services:
  influx:
    image: influxdb:2.7.6-alpine
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=tracksight
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=tracksight
      - INFLUXDB_USER_PASSWORD=tracksight
  backend:
    user: root
    build:
      context: ../../
      dockerfile: ./software/tracksight/backend/Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend/logs:/backend/logs
      - ../../can_bus:/can_bus
  frontend:
    build: ./frontend
    ports:
      - "80:3000"