#pragma once

#define AUX1_MIN_CURRENT 0.0f
#define AUX1_MAX_CURRENT 1.0f
#define AUX2_MIN_CURRENT 0.0f
#define AUX2_MAX_CURRENT 1.0f
#define AIR_SHUTDOWN_MIN_CURRENT 0.0f
#define AIR_SHUTDOWN_MAX_CURRENT 2.5f
#define CAN_MIN_CURRENT 0.0f
#define CAN_MAX_CURRENT 2.5f
#define BACK_LEFT_INVERTER_MIN_CURRENT 0.0f
#define BACK_LEFT_INVERTER_MAX_CURRENT 2.5f
#define BACK_RIGHT_INVERTER_MIN_CURRENT 0.0f
#define BACK_RIGHT_INVERTER_MAX_CURRENT 2.5f
#define FRONT_LEFT_INVERTER_MIN_CURRENT 0.0f
#define FRONT_LEFT_INVERTER_MAX_CURRENT 2.5f
#define FRONT_RIGHT_INVERTER_MIN_CURRENT 0.0f
#define FRONT_RIGHT_INVERTER_MAX_CURRENT 2.5f
