#pragma once

#define AUX1_MIN_CURRENT 0.0f
#define AUX1_MAX_CURRENT 1.0f
#define AUX2_MIN_CURRENT 0.0f
#define AUX2_MAX_CURRENT 1.0f
#define LEFT_INVERTER_MIN_CURRENT 0.0f
#define LEFT_INVERTER_MAX_CURRENT 2.5f
#define RIGHT_INVERTER_MIN_CURRENT 0.0f
#define RIGHT_INVERTER_MAX_CURRENT 2.5f
#define ENERGY_METER_MIN_CURRENT 0.0f
#define ENERGY_METER_MAX_CURRENT 2.5f
#define CAN_MIN_CURRENT 0.0f
#define CAN_MAX_CURRENT 2.5f
#define AIR_SHUTDOWN_MIN_CURRENT 0.0f
#define AIR_SHUTDOWN_MAX_CURRENT 2.5f

#define CS_AIR_MIN_CURRENT
#define CS_AIR_MAX_CURRENT
#define CS_LVPWR_MIN_CURRENT
#define CS_LVPWR_MAX_CURRENT
#define CS_AUX1_MIN_CURRENT
#define CS_AUX1_MAX_CURRENT
#define CS_AUX2_MIN_CURRENT
#define CS_AUX2_MAX_CURRENT
#define CS_DI_FRONT_LHS_MIN_CURRENT
#define CS_DI_FRONT_LHS_MAX_CURRENT
#define CS_DI_FRONT_RHS_MIN_CURRENT
#define CS_DI_FRONT_RHS_MAX_CURRENT
#define CS_DI_REAR_LHS_MIN_CURRENT
#define CS_DI_REAR_LHS_MAX_CURRENT
#define CS_DI_REAR_RHS_MIN_CURRENT
#define CS_DI_REAR_RHS_MAX_CURRENT
