//
// Created by formulae on 11/02/23.
//

#ifndef FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H
#define FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H

#define

#endif //FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H
