//
// Created by formulae on 11/02/23.
//

#ifndef FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H
#define FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H

#define WHEEL_RADIUS_m
#define FRONT_AXLE_LENGTH_m
#define POWER_TO_TORQUE_CONVERSION_FACTOR  9550 //as specified in the manual for the emrax 188 motors
#define HARD_POWER_LIMIT_kW 80

#endif //FORMULA_ELECTRIC_FIRMWARE_TORQUEVECTORING_CONSTANTS_H
