name: dimos
description: "Application which runs on the dashboard of the UBC Formula Electric team."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  linux_can: ^0.2.0
  provider: ^6.1.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fe_logo.svg
