name: Build DBC Action
description: Builds the DBC file from the JSON files to ./hexray.dbc
runs:
  using: "composite"
  steps:
    - name: Generate Hexray DBC
      shell: bash
      run: |
        cargo run --release --manifest-path scripts/code_generation/jsoncan-rust/Cargo.toml --bin cppcodegen -- \
          --only-dbc --board VC --can-data-dir "can_bus/hexray" --output-dir . --dbc-output "hexray.dbc"
