add-symbol-file "./build_fw_deploy/firmware/quadruna/CRIT/quadruna_CRIT.elf"
add-symbol-file "./build_fw_deploy/firmware/quadruna/RSM/quadruna_RSM.elf"
add-symbol-file "./build_fw_deploy/firmware/quadruna/BMS/quadruna_BMS_app.elf"
add-symbol-file "./build_fw_deploy/firmware/quadruna/FSM/quadruna_FSM.elf"
add-symbol-file "./build_fw_deploy/firmware/quadruna/VC/quadruna_VC_app.elf"
