#!/bin/bash

ROOT_DIR="${0:A:h}"

if [[ -z "$1" ]]; then
    echo "Please specify an action"
    exit 1
fi

case "$1" in
    cmake)
        cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DPLATFORM=arm -S ./boards -B ./boards/cmake-build-embedded
        ;;
    be)
        make -C ./boards/cmake-build-embedded "$2"
        ;;
esac
