"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

class _GpioNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_LEDB: _GpioNetName.ValueType
    GPIO_BSPD_OK: _GpioNetName.ValueType
    GPIO_ACCEL_BRAKE_OK: _GpioNetName.ValueType
    GPIO_nBRAKE_PRESS_3V3: _GpioNetName.ValueType
    GPIO_nHIGH_CURRENT_BSPD: _GpioNetName.ValueType
    GPIO_MSD_SHDN_SNS: _GpioNetName.ValueType
    GPIO_HV_P_INTLCK_SNS: _GpioNetName.ValueType
    GPIO_HV_N_INTLCK_SNS: _GpioNetName.ValueType
    GPIO_IMD_LATCH: _GpioNetName.ValueType
    GPIO_DIAG: _GpioNetName.ValueType
    GPIO_SD_CD: _GpioNetName.ValueType
    GPIO_LEDR: _GpioNetName.ValueType
    GPIO_SPI_CS_LS: _GpioNetName.ValueType
    GPIO_TSENSE_SEL0: _GpioNetName.ValueType
    GPIO_TSENSE_SEL1: _GpioNetName.ValueType
    GPIO_TSENSE_SEL2: _GpioNetName.ValueType
    GPIO_BSPD_TEST_EN: _GpioNetName.ValueType
    GPIO_TS_ISENSE_OCSC_OK_3V3: _GpioNetName.ValueType
    GPIO_SPI_CS_HS: _GpioNetName.ValueType
    GPIO_BMS_OK: _GpioNetName.ValueType
    GPIO_nEVSE_I_LIM_GPIO: _GpioNetName.ValueType
    GPIO_IR_P_EN: _GpioNetName.ValueType
    GPIO_SHDN_EN: _GpioNetName.ValueType
    GPIO_BMS_LATCH: _GpioNetName.ValueType
    GPIO_IMD_OK: _GpioNetName.ValueType
    GPIO_BSPD_LATCH: _GpioNetName.ValueType
    GPIO_PRE_CHARGE_EN: _GpioNetName.ValueType
    GPIO_FB_STBY_SHDN: _GpioNetName.ValueType
    GPIO_FAN_EN: _GpioNetName.ValueType
    GPIO_FAN_PGOOD: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_LEDB: GpioNetName.ValueType
GPIO_BSPD_OK: GpioNetName.ValueType
GPIO_ACCEL_BRAKE_OK: GpioNetName.ValueType
GPIO_nBRAKE_PRESS_3V3: GpioNetName.ValueType
GPIO_nHIGH_CURRENT_BSPD: GpioNetName.ValueType
GPIO_MSD_SHDN_SNS: GpioNetName.ValueType
GPIO_HV_P_INTLCK_SNS: GpioNetName.ValueType
GPIO_HV_N_INTLCK_SNS: GpioNetName.ValueType
GPIO_IMD_LATCH: GpioNetName.ValueType
GPIO_DIAG: GpioNetName.ValueType
GPIO_SD_CD: GpioNetName.ValueType
GPIO_LEDR: GpioNetName.ValueType
GPIO_SPI_CS_LS: GpioNetName.ValueType
GPIO_TSENSE_SEL0: GpioNetName.ValueType
GPIO_TSENSE_SEL1: GpioNetName.ValueType
GPIO_TSENSE_SEL2: GpioNetName.ValueType
GPIO_BSPD_TEST_EN: GpioNetName.ValueType
GPIO_TS_ISENSE_OCSC_OK_3V3: GpioNetName.ValueType
GPIO_SPI_CS_HS: GpioNetName.ValueType
GPIO_BMS_OK: GpioNetName.ValueType
GPIO_nEVSE_I_LIM_GPIO: GpioNetName.ValueType
GPIO_IR_P_EN: GpioNetName.ValueType
GPIO_SHDN_EN: GpioNetName.ValueType
GPIO_BMS_LATCH: GpioNetName.ValueType
GPIO_IMD_OK: GpioNetName.ValueType
GPIO_BSPD_LATCH: GpioNetName.ValueType
GPIO_PRE_CHARGE_EN: GpioNetName.ValueType
GPIO_FB_STBY_SHDN: GpioNetName.ValueType
GPIO_FAN_EN: GpioNetName.ValueType
GPIO_FAN_PGOOD: GpioNetName.ValueType
Global___GpioNetName: _TypeAlias = GpioNetName

class _AdcNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_FAN_ISNS: _AdcNetName.ValueType
    ADC_TS_VSENSE_P: _AdcNetName.ValueType
    ADC_TS_VSENSE_N: _AdcNetName.ValueType
    ADC_SHDN_ISNS: _AdcNetName.ValueType
    ADC_EMETER_THERM_SNS: _AdcNetName.ValueType
    ADC_TS_ISNS_400A: _AdcNetName.ValueType
    ADC_TS_ISNS_50A: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_FAN_ISNS: AdcNetName.ValueType
ADC_TS_VSENSE_P: AdcNetName.ValueType
ADC_TS_VSENSE_N: AdcNetName.ValueType
ADC_SHDN_ISNS: AdcNetName.ValueType
ADC_EMETER_THERM_SNS: AdcNetName.ValueType
ADC_TS_ISNS_400A: AdcNetName.ValueType
ADC_TS_ISNS_50A: AdcNetName.ValueType
Global___AdcNetName: _TypeAlias = AdcNetName

class _SpiNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    SPI_LTC6813_LS: _SpiNetName.ValueType
    SPI_LTC6813_HS: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
SPI_LTC6813_LS: SpiNetName.ValueType
SPI_LTC6813_HS: SpiNetName.ValueType
Global___SpiNetName: _TypeAlias = SpiNetName