"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

class _GpioNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_BOOT: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_TELEM_SIG: _GpioNetName.ValueType
    GPIO_PUSH_DRIVE_SIG: _GpioNetName.ValueType
    GPIO_ROT_S: _GpioNetName.ValueType
    GPIO_ROT_B: _GpioNetName.ValueType
    GPIO_ROT_A: _GpioNetName.ValueType
    GPIO_LAUNCH_CONTROL_SIG: _GpioNetName.ValueType
    GPIO_TORQUE_VECTORING_SIG: _GpioNetName.ValueType
    GPIO_REGEN_SIG: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_BOOT: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_TELEM_SIG: GpioNetName.ValueType
GPIO_PUSH_DRIVE_SIG: GpioNetName.ValueType
GPIO_ROT_S: GpioNetName.ValueType
GPIO_ROT_B: GpioNetName.ValueType
GPIO_ROT_A: GpioNetName.ValueType
GPIO_LAUNCH_CONTROL_SIG: GpioNetName.ValueType
GPIO_TORQUE_VECTORING_SIG: GpioNetName.ValueType
GPIO_REGEN_SIG: GpioNetName.ValueType
Global___GpioNetName: _TypeAlias = GpioNetName

class _SpiNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    LED: _SpiNetName.ValueType
    SEVEN_SEG: _SpiNetName.ValueType
    PWR_CHG: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
LED: SpiNetName.ValueType
SEVEN_SEG: SpiNetName.ValueType
PWR_CHG: SpiNetName.ValueType
Global___SpiNetName: _TypeAlias = SpiNetName