"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_NTP: _GpioNetName.ValueType
    GPIO_BUZZER_PWR_EN: _GpioNetName.ValueType
    GPIO_TSIM_RED_EN: _GpioNetName.ValueType
    GPIO_NTSIM_GRN_EN: _GpioNetName.ValueType
    GPIO_R_SHDN_SENSE: _GpioNetName.ValueType
    GPIO_L_SHDN_SENSE: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_BOOT: _GpioNetName.ValueType
    GPIO_SD_PRESENT: _GpioNetName.ValueType
    GPIO_900M: _GpioNetName.ValueType
    GPIO_SD_FAIL: _GpioNetName.ValueType
    GPIO_D_P_PULLUP: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper): ...

GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_NTP: GpioNetName.ValueType
GPIO_BUZZER_PWR_EN: GpioNetName.ValueType
GPIO_TSIM_RED_EN: GpioNetName.ValueType
GPIO_NTSIM_GRN_EN: GpioNetName.ValueType
GPIO_R_SHDN_SENSE: GpioNetName.ValueType
GPIO_L_SHDN_SENSE: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_BOOT: GpioNetName.ValueType
GPIO_SD_PRESENT: GpioNetName.ValueType
GPIO_900M: GpioNetName.ValueType
GPIO_SD_FAIL: GpioNetName.ValueType
GPIO_D_P_PULLUP: GpioNetName.ValueType
Global___GpioNetName: typing_extensions.TypeAlias = GpioNetName

class _UartNetName:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UartNetNameEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UartNetName.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UART_NET_NAME_UNSPECIFIED: _UartNetName.ValueType
    UART_RADIO: _UartNetName.ValueType

class UartNetName(_UartNetName, metaclass=_UartNetNameEnumTypeWrapper): ...

UART_NET_NAME_UNSPECIFIED: UartNetName.ValueType
UART_RADIO: UartNetName.ValueType
Global___UartNetName: typing_extensions.TypeAlias = UartNetName
