"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

class _GpioNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_6: _GpioNetName.ValueType
    GPIO_5: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_6: GpioNetName.ValueType
GPIO_5: GpioNetName.ValueType
Global___GpioNetName: _TypeAlias = GpioNetName