"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_BOTS_3v3: _GpioNetName.ValueType
    GPIO_COCKPIT_SHDN_3v3: _GpioNetName.ValueType
    GPIO_IMU_NSS: _GpioNetName.ValueType
    GPIO_IMU_FSYNC: _GpioNetName.ValueType
    GPIO_NSUSP_FL_OCSC: _GpioNetName.ValueType
    GPIO_NSUSP_FR_OCSC: _GpioNetName.ValueType
    GPIO_FR_INT_3v3: _GpioNetName.ValueType
    GPIO_FL_INT_3v3: _GpioNetName.ValueType
    GPIO_DEBUG_LED: _GpioNetName.ValueType
    GPIO_NSTR_ANGLE_OCSC: _GpioNetName.ValueType
    GPIO_NBPS_F_OCSC: _GpioNetName.ValueType
    GPIO_BOOT_LED: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_BOTS_3v3: GpioNetName.ValueType
GPIO_COCKPIT_SHDN_3v3: GpioNetName.ValueType
GPIO_IMU_NSS: GpioNetName.ValueType
GPIO_IMU_FSYNC: GpioNetName.ValueType
GPIO_NSUSP_FL_OCSC: GpioNetName.ValueType
GPIO_NSUSP_FR_OCSC: GpioNetName.ValueType
GPIO_FR_INT_3v3: GpioNetName.ValueType
GPIO_FL_INT_3v3: GpioNetName.ValueType
GPIO_DEBUG_LED: GpioNetName.ValueType
GPIO_NSTR_ANGLE_OCSC: GpioNetName.ValueType
GPIO_NBPS_F_OCSC: GpioNetName.ValueType
GPIO_BOOT_LED: GpioNetName.ValueType
Global___GpioNetName: typing_extensions.TypeAlias = GpioNetName

class _AdcNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_SUSP_FL: _AdcNetName.ValueType
    ADC_SUSP_FR: _AdcNetName.ValueType
    ADC_APPS2: _AdcNetName.ValueType
    ADC_BPS_F: _AdcNetName.ValueType
    ADC_STR_ANGLE: _AdcNetName.ValueType
    ADC_APPS1: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_SUSP_FL: AdcNetName.ValueType
ADC_SUSP_FR: AdcNetName.ValueType
ADC_APPS2: AdcNetName.ValueType
ADC_BPS_F: AdcNetName.ValueType
ADC_STR_ANGLE: AdcNetName.ValueType
ADC_APPS1: AdcNetName.ValueType
Global___AdcNetName: typing_extensions.TypeAlias = AdcNetName

class _SpiNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    SPI_IMU: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
SPI_IMU: SpiNetName.ValueType
Global___SpiNetName: typing_extensions.TypeAlias = SpiNetName