"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

class _GpioNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_BRAKE_LIGHT_EN: _GpioNetName.ValueType
    GPIO_RL_INT: _GpioNetName.ValueType
    GPIO_IMU_CS: _GpioNetName.ValueType
    GPIO_IMU_INT: _GpioNetName.ValueType
    GPIO_IMU_FSYNC: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RR_OCSC: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RL_OCSC: _GpioNetName.ValueType
    GPIO_BRAKE_OCSC_OK: _GpioNetName.ValueType
    GPIO_D_P_PULLUP: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_BRAKE_LIGHT_EN: GpioNetName.ValueType
GPIO_RL_INT: GpioNetName.ValueType
GPIO_IMU_CS: GpioNetName.ValueType
GPIO_IMU_INT: GpioNetName.ValueType
GPIO_IMU_FSYNC: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RR_OCSC: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RL_OCSC: GpioNetName.ValueType
GPIO_BRAKE_OCSC_OK: GpioNetName.ValueType
GPIO_D_P_PULLUP: GpioNetName.ValueType
Global___GpioNetName: _TypeAlias = GpioNetName

class _AdcNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_LC3_OUT: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RL_3V3: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RR_3V3: _AdcNetName.ValueType
    ADC_BPS_3V3: _AdcNetName.ValueType
    ADC_nBSPD_BRAKE_PRESSED: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_LC3_OUT: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RL_3V3: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RR_3V3: AdcNetName.ValueType
ADC_BPS_3V3: AdcNetName.ValueType
ADC_nBSPD_BRAKE_PRESSED: AdcNetName.ValueType
Global___AdcNetName: _TypeAlias = AdcNetName

class _I2cNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _I2cNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_I2cNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    I2C_NET_NAME_UNSPECIFIED: _I2cNetName.ValueType
    I2C_R_PUMP: _I2cNetName.ValueType

class I2cNetName(_I2cNetName, metaclass=_I2cNetNameEnumTypeWrapper):
    ...
I2C_NET_NAME_UNSPECIFIED: I2cNetName.ValueType
I2C_R_PUMP: I2cNetName.ValueType
Global___I2cNetName: _TypeAlias = I2cNetName

class _SpiNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    SPI_IMU: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
SPI_IMU: SpiNetName.ValueType
Global___SpiNetName: _TypeAlias = SpiNetName