"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_BRAKE_LIGHT_EN: _GpioNetName.ValueType
    GPIO_RL_INT: _GpioNetName.ValueType
    GPIO_IMU_CS: _GpioNetName.ValueType
    GPIO_IMU_INT: _GpioNetName.ValueType
    GPIO_IMU_FSYNC: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RR_OCSC: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RL_OCSC: _GpioNetName.ValueType
    GPIO_BRAKE_OCSC_OK: _GpioNetName.ValueType
    GPIO_D_P_PULLUP: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_BRAKE_LIGHT_EN: GpioNetName.ValueType
GPIO_RL_INT: GpioNetName.ValueType
GPIO_IMU_CS: GpioNetName.ValueType
GPIO_IMU_INT: GpioNetName.ValueType
GPIO_IMU_FSYNC: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RR_OCSC: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RL_OCSC: GpioNetName.ValueType
GPIO_BRAKE_OCSC_OK: GpioNetName.ValueType
GPIO_D_P_PULLUP: GpioNetName.ValueType
Global___GpioNetName: typing_extensions.TypeAlias = GpioNetName

class _AdcNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_LC3_OUT: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RL_3V3: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RR_3V3: _AdcNetName.ValueType
    ADC_BPS_3V3: _AdcNetName.ValueType
    ADC_nBSPD_BRAKE_PRESSED: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_LC3_OUT: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RL_3V3: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RR_3V3: AdcNetName.ValueType
ADC_BPS_3V3: AdcNetName.ValueType
ADC_nBSPD_BRAKE_PRESSED: AdcNetName.ValueType
Global___AdcNetName: typing_extensions.TypeAlias = AdcNetName

class _I2cNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _I2cNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_I2cNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    I2C_NET_NAME_UNSPECIFIED: _I2cNetName.ValueType
    I2C_R_PUMP: _I2cNetName.ValueType

class I2cNetName(_I2cNetName, metaclass=_I2cNetNameEnumTypeWrapper):
    ...
I2C_NET_NAME_UNSPECIFIED: I2cNetName.ValueType
I2C_R_PUMP: I2cNetName.ValueType
Global___I2cNetName: typing_extensions.TypeAlias = I2cNetName

class _SpiNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    SPI_IMU: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
SPI_IMU: SpiNetName.ValueType
Global___SpiNetName: typing_extensions.TypeAlias = SpiNetName