"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from . import bms_pb2
import builtins
from . import crit_pb2
from . import dam_pb2
from . import f4dev_pb2
from . import fsm_pb2
import google.protobuf.descriptor
import google.protobuf.message
from . import rsm_pb2
import sys
import typing
from . import vc_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GpioNetName(google.protobuf.message.Message):
    """GPIOs"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    F4DEV_NET_NAME_FIELD_NUMBER: builtins.int
    CRIT_NET_NAME_FIELD_NUMBER: builtins.int
    DAM_NET_NAME_FIELD_NUMBER: builtins.int
    RSM_NET_NAME_FIELD_NUMBER: builtins.int
    FSM_NET_NAME_FIELD_NUMBER: builtins.int
    BMS_NET_NAME_FIELD_NUMBER: builtins.int
    VC_NET_NAME_FIELD_NUMBER: builtins.int
    f4dev_net_name: f4dev_pb2.GpioNetName.ValueType
    crit_net_name: crit_pb2.GpioNetName.ValueType
    dam_net_name: dam_pb2.GpioNetName.ValueType
    rsm_net_name: rsm_pb2.GpioNetName.ValueType
    fsm_net_name: fsm_pb2.GpioNetName.ValueType
    bms_net_name: bms_pb2.GpioNetName.ValueType
    vc_net_name: vc_pb2.GpioNetName.ValueType

    def __init__(
        self,
        *,
        f4dev_net_name: f4dev_pb2.GpioNetName.ValueType = ...,
        crit_net_name: crit_pb2.GpioNetName.ValueType = ...,
        dam_net_name: dam_pb2.GpioNetName.ValueType = ...,
        rsm_net_name: rsm_pb2.GpioNetName.ValueType = ...,
        fsm_net_name: fsm_pb2.GpioNetName.ValueType = ...,
        bms_net_name: bms_pb2.GpioNetName.ValueType = ...,
        vc_net_name: vc_pb2.GpioNetName.ValueType = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bms_net_name",
            b"bms_net_name",
            "crit_net_name",
            b"crit_net_name",
            "dam_net_name",
            b"dam_net_name",
            "f4dev_net_name",
            b"f4dev_net_name",
            "fsm_net_name",
            b"fsm_net_name",
            "name",
            b"name",
            "rsm_net_name",
            b"rsm_net_name",
            "vc_net_name",
            b"vc_net_name",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bms_net_name",
            b"bms_net_name",
            "crit_net_name",
            b"crit_net_name",
            "dam_net_name",
            b"dam_net_name",
            "f4dev_net_name",
            b"f4dev_net_name",
            "fsm_net_name",
            b"fsm_net_name",
            "name",
            b"name",
            "rsm_net_name",
            b"rsm_net_name",
            "vc_net_name",
            b"vc_net_name",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["name", b"name"]
    ) -> (
        typing.Literal[
            "f4dev_net_name",
            "crit_net_name",
            "dam_net_name",
            "rsm_net_name",
            "fsm_net_name",
            "bms_net_name",
            "vc_net_name",
        ]
        | None
    ): ...

Global___GpioNetName: typing_extensions.TypeAlias = GpioNetName

@typing.final
class GpioReadRequest(google.protobuf.message.Message):
    """GPIO read request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int

    @property
    def net_name(self) -> Global___GpioNetName: ...
    def __init__(self, *, net_name: Global___GpioNetName | None = ...) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> None: ...

Global___GpioReadRequest: typing_extensions.TypeAlias = GpioReadRequest

@typing.final
class GpioReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.bool

    def __init__(self, *, value: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

Global___GpioReadResponse: typing_extensions.TypeAlias = GpioReadResponse

@typing.final
class GpioWriteRequest(google.protobuf.message.Message):
    """GPIO write request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.bool

    @property
    def net_name(self) -> Global___GpioNetName: ...
    def __init__(
        self, *, net_name: Global___GpioNetName | None = ..., value: builtins.bool = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["net_name", b"net_name", "value", b"value"]
    ) -> None: ...

Global___GpioWriteRequest: typing_extensions.TypeAlias = GpioWriteRequest

@typing.final
class GpioWriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool

    def __init__(self, *, success: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___GpioWriteResponse: typing_extensions.TypeAlias = GpioWriteResponse

@typing.final
class AdcNetName(google.protobuf.message.Message):
    """ADCs"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RSM_NET_NAME_FIELD_NUMBER: builtins.int
    FSM_NET_NAME_FIELD_NUMBER: builtins.int
    BMS_NET_NAME_FIELD_NUMBER: builtins.int
    VC_NET_NAME_FIELD_NUMBER: builtins.int
    rsm_net_name: rsm_pb2.AdcNetName.ValueType
    fsm_net_name: fsm_pb2.AdcNetName.ValueType
    bms_net_name: bms_pb2.AdcNetName.ValueType
    vc_net_name: vc_pb2.AdcNetName.ValueType

    def __init__(
        self,
        *,
        rsm_net_name: rsm_pb2.AdcNetName.ValueType = ...,
        fsm_net_name: fsm_pb2.AdcNetName.ValueType = ...,
        bms_net_name: bms_pb2.AdcNetName.ValueType = ...,
        vc_net_name: vc_pb2.AdcNetName.ValueType = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bms_net_name",
            b"bms_net_name",
            "fsm_net_name",
            b"fsm_net_name",
            "name",
            b"name",
            "rsm_net_name",
            b"rsm_net_name",
            "vc_net_name",
            b"vc_net_name",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bms_net_name",
            b"bms_net_name",
            "fsm_net_name",
            b"fsm_net_name",
            "name",
            b"name",
            "rsm_net_name",
            b"rsm_net_name",
            "vc_net_name",
            b"vc_net_name",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["name", b"name"]
    ) -> (
        typing.Literal["rsm_net_name", "fsm_net_name", "bms_net_name", "vc_net_name"]
        | None
    ): ...

Global___AdcNetName: typing_extensions.TypeAlias = AdcNetName

@typing.final
class AdcReadRequest(google.protobuf.message.Message):
    """ADC read request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int

    @property
    def net_name(self) -> Global___AdcNetName: ...
    def __init__(self, *, net_name: Global___AdcNetName | None = ...) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> None: ...

Global___AdcReadRequest: typing_extensions.TypeAlias = AdcReadRequest

@typing.final
class AdcReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.float

    def __init__(self, *, value: builtins.float = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

Global___AdcReadResponse: typing_extensions.TypeAlias = AdcReadResponse

@typing.final
class I2cNetName(google.protobuf.message.Message):
    """I2Cs"""
    DESCRIPTOR: _descriptor.Descriptor
    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    VC_NET_NAME_FIELD_NUMBER: _builtins.int
    rsm_net_name: _rsm_pb2.I2cNetName.ValueType
    vc_net_name: _vc_pb2.I2cNetName.ValueType

    def __init__(self, *, rsm_net_name: _rsm_pb2.I2cNetName.ValueType=..., vc_net_name: _vc_pb2.I2cNetName.ValueType=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['name', b'name', 'rsm_net_name', b'rsm_net_name', 'vc_net_name', b'vc_net_name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['name', b'name', 'rsm_net_name', b'rsm_net_name', 'vc_net_name', b'vc_net_name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal['rsm_net_name', 'vc_net_name']
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal['name', b'name']

@typing.final
class I2cReadyRequest(google.protobuf.message.Message):
    """I2C ready check request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int

    @property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(self, *, net_name: Global___I2cNetName | None = ...) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> None: ...

Global___I2cReadyRequest: typing_extensions.TypeAlias = I2cReadyRequest

@typing.final
class I2cReadyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    READY_FIELD_NUMBER: builtins.int
    ready: builtins.bool

    def __init__(self, *, ready: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["ready", b"ready"]) -> None: ...

Global___I2cReadyResponse: typing_extensions.TypeAlias = I2cReadyResponse

@typing.final
class I2cReceiveRequest(google.protobuf.message.Message):
    """I2C receive data request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int

    @property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self, *, net_name: Global___I2cNetName | None = ..., length: builtins.int = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["length", b"length", "net_name", b"net_name"]
    ) -> None: ...

Global___I2cReceiveRequest: typing_extensions.TypeAlias = I2cReceiveRequest

@typing.final
class I2cReceiveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

Global___I2cReceiveResponse: typing_extensions.TypeAlias = I2cReceiveResponse

@typing.final
class I2cTransmitRequest(google.protobuf.message.Message):
    """I2C transmit data request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    @property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self, *, net_name: Global___I2cNetName | None = ..., data: builtins.bytes = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["data", b"data", "net_name", b"net_name"]
    ) -> None: ...

Global___I2cTransmitRequest: typing_extensions.TypeAlias = I2cTransmitRequest

@typing.final
class I2cTransmitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool

    def __init__(self, *, success: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___I2cTransmitResponse: typing_extensions.TypeAlias = I2cTransmitResponse

@typing.final
class I2cMemoryReadRequest(google.protobuf.message.Message):
    """I2C read memory request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    MEMORY_ADDRESS_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    memory_address: builtins.int
    length: builtins.int

    @property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        memory_address: builtins.int = ...,
        length: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "length",
            b"length",
            "memory_address",
            b"memory_address",
            "net_name",
            b"net_name",
        ],
    ) -> None: ...

Global___I2cMemoryReadRequest: typing_extensions.TypeAlias = I2cMemoryReadRequest

@typing.final
class I2cMemoryReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

Global___I2cMemoryReadResponse: typing_extensions.TypeAlias = I2cMemoryReadResponse

@typing.final
class I2cMemoryWriteRequest(google.protobuf.message.Message):
    """I2C write memory request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    MEMORY_ADDRESS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    memory_address: builtins.int
    data: builtins.bytes

    @property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        memory_address: builtins.int = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "data",
            b"data",
            "memory_address",
            b"memory_address",
            "net_name",
            b"net_name",
        ],
    ) -> None: ...

Global___I2cMemoryWriteRequest: typing_extensions.TypeAlias = I2cMemoryWriteRequest

@typing.final
class I2cMemoryWriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool

    def __init__(self, *, success: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___I2cMemoryWriteResponse: typing_extensions.TypeAlias = I2cMemoryWriteResponse

@typing.final
class SpiNetName(google.protobuf.message.Message):
    """SPIs"""
    DESCRIPTOR: _descriptor.Descriptor
    BMS_NET_NAME_FIELD_NUMBER: _builtins.int
    CRIT_NET_NAME_FIELD_NUMBER: _builtins.int
    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    FSM_NET_NAME_FIELD_NUMBER: _builtins.int
    VC_NET_NAME_FIELD_NUMBER: _builtins.int
    bms_net_name: _bms_pb2.SpiNetName.ValueType
    crit_net_name: _crit_pb2.SpiNetName.ValueType
    rsm_net_name: _rsm_pb2.SpiNetName.ValueType
    fsm_net_name: _fsm_pb2.SpiNetName.ValueType
    vc_net_name: _vc_pb2.SpiNetName.ValueType

    def __init__(self, *, bms_net_name: _bms_pb2.SpiNetName.ValueType=..., crit_net_name: _crit_pb2.SpiNetName.ValueType=..., rsm_net_name: _rsm_pb2.SpiNetName.ValueType=..., fsm_net_name: _fsm_pb2.SpiNetName.ValueType=..., vc_net_name: _vc_pb2.SpiNetName.ValueType=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['bms_net_name', b'bms_net_name', 'crit_net_name', b'crit_net_name', 'fsm_net_name', b'fsm_net_name', 'name', b'name', 'rsm_net_name', b'rsm_net_name', 'vc_net_name', b'vc_net_name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['bms_net_name', b'bms_net_name', 'crit_net_name', b'crit_net_name', 'fsm_net_name', b'fsm_net_name', 'name', b'name', 'rsm_net_name', b'rsm_net_name', 'vc_net_name', b'vc_net_name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal['bms_net_name', 'crit_net_name', 'rsm_net_name', 'fsm_net_name', 'vc_net_name']
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal['name', b'name']

@typing.final
class SpiTransmitRequest(google.protobuf.message.Message):
    """SPI transmit data request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    @property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self, *, net_name: Global___SpiNetName | None = ..., data: builtins.bytes = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["data", b"data", "net_name", b"net_name"]
    ) -> None: ...

Global___SpiTransmitRequest: typing_extensions.TypeAlias = SpiTransmitRequest

@typing.final
class SpiTransmitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool

    def __init__(self, *, success: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___SpiTransmitResponse: typing_extensions.TypeAlias = SpiTransmitResponse

@typing.final
class SpiReceiveRequest(google.protobuf.message.Message):
    """SPI receive data request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int

    @property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self, *, net_name: Global___SpiNetName | None = ..., length: builtins.int = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["length", b"length", "net_name", b"net_name"]
    ) -> None: ...

Global___SpiReceiveRequest: typing_extensions.TypeAlias = SpiReceiveRequest

@typing.final
class SpiReceiveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

Global___SpiReceiveResponse: typing_extensions.TypeAlias = SpiReceiveResponse

@typing.final
class SpiTransactionRequest(google.protobuf.message.Message):
    """SPI full-duplex request/response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: builtins.int
    TX_DATA_FIELD_NUMBER: builtins.int
    RX_LENGTH_FIELD_NUMBER: builtins.int
    tx_data: builtins.bytes
    rx_length: builtins.int

    @property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___SpiNetName | None = ...,
        tx_data: builtins.bytes = ...,
        rx_length: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["net_name", b"net_name"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "net_name", b"net_name", "rx_length", b"rx_length", "tx_data", b"tx_data"
        ],
    ) -> None: ...

Global___SpiTransactionRequest: typing_extensions.TypeAlias = SpiTransactionRequest

@typing.final
class SpiTransactionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RX_DATA_FIELD_NUMBER: builtins.int
    rx_data: builtins.bytes

    def __init__(self, *, rx_data: builtins.bytes = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["rx_data", b"rx_data"]) -> None: ...

Global___SpiTransactionResponse: typing_extensions.TypeAlias = SpiTransactionResponse

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___SpiTransactionResponse: _TypeAlias = SpiTransactionResponse

@_typing.final
class UartNetName(_message.Message):
    """UART"""
    DESCRIPTOR: _descriptor.Descriptor
    DAM_NET_NAME_FIELD_NUMBER: _builtins.int
    dam_net_name: _dam_pb2.UartNetName.ValueType

    def __init__(self, *, dam_net_name: _dam_pb2.UartNetName.ValueType=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['dam_net_name', b'dam_net_name', 'name', b'name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['dam_net_name', b'dam_net_name', 'name', b'name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal['dam_net_name']
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal['name', b'name']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None:
        ...
Global___UartNetName: _TypeAlias = UartNetName

@_typing.final
class UartTransmitRequest(_message.Message):
    """Uart Transmit"""
    DESCRIPTOR: _descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes

    @_builtins.property
    def net_name(self) -> Global___UartNetName:
        ...

    def __init__(self, *, net_name: Global___UartNetName | None=..., data: _builtins.bytes=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['net_name', b'net_name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['data', b'data', 'net_name', b'net_name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___UartTransmitRequest: _TypeAlias = UartTransmitRequest

@_typing.final
class UartTransmitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool

    def __init__(self, *, success: _builtins.bool=...) -> None:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['success', b'success']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___UartTransmitResponse: _TypeAlias = UartTransmitResponse

@_typing.final
class UartRecieveRequest(_message.Message):
    """Uart receieve"""
    DESCRIPTOR: _descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    length: _builtins.int

    @_builtins.property
    def net_name(self) -> Global___UartNetName:
        ...

    def __init__(self, *, net_name: Global___UartNetName | None=..., length: _builtins.int=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['net_name', b'net_name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['length', b'length', 'net_name', b'net_name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___UartRecieveRequest: _TypeAlias = UartRecieveRequest

@_typing.final
class UartReceiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes

    def __init__(self, *, data: _builtins.bytes=...) -> None:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['data', b'data']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___UartReceiveResponse: _TypeAlias = UartReceiveResponse

@_typing.final
class PwmNetName(_message.Message):
    """PWM"""
    DESCRIPTOR: _descriptor.Descriptor
    CRIT_NET_NAME_FIELD_NUMBER: _builtins.int
    crit_net_name: _crit_pb2.PwmNetName.ValueType

    def __init__(self, *, crit_net_name: _crit_pb2.PwmNetName.ValueType=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['crit_net_name', b'crit_net_name', 'name', b'name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['crit_net_name', b'crit_net_name', 'name', b'name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal['crit_net_name']
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal['name', b'name']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None:
        ...
Global___PwmNetName: _TypeAlias = PwmNetName

@_typing.final
class PwmSetRequest(_message.Message):
    """PWM set"""
    DESCRIPTOR: _descriptor.Descriptor
    NET_NAME_FIELD_NUMBER: _builtins.int
    ENABLE_FIELD_NUMBER: _builtins.int
    DUTY_CYCLE_FIELD_NUMBER: _builtins.int
    enable: _builtins.bool
    duty_cycle: _builtins.float
    '0.0 to 1.0'

    @_builtins.property
    def net_name(self) -> Global___PwmNetName:
        ...

    def __init__(self, *, net_name: Global___PwmNetName | None=..., enable: _builtins.bool=..., duty_cycle: _builtins.float=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['net_name', b'net_name']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['duty_cycle', b'duty_cycle', 'enable', b'enable', 'net_name', b'net_name']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___PwmSetRequest: _TypeAlias = PwmSetRequest

@_typing.final
class PwmSetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool

    def __init__(self, *, success: _builtins.bool=...) -> None:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['success', b'success']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
Global___PwmSetResponse: _TypeAlias = PwmSetResponse

@_typing.final
class ChimeraV2Request(_message.Message):
    """
    Wrapper around all messages

    There is no RPC support in nanopb, so we construct our own request/response protocol.
    Some interesting projects to like at in the future if this ever gets too cumbersome are:
    - https://github.com/EmbeddedRPC/erpc
    - https://github.com/d21d3q/nanogrpc
    """
    DESCRIPTOR: _descriptor.Descriptor
    GPIO_READ_FIELD_NUMBER: _builtins.int
    GPIO_WRITE_FIELD_NUMBER: _builtins.int
    ADC_READ_FIELD_NUMBER: _builtins.int
    I2C_READY_FIELD_NUMBER: _builtins.int
    I2C_RECEIVE_FIELD_NUMBER: _builtins.int
    I2C_TRANSMIT_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_READ_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_WRITE_FIELD_NUMBER: _builtins.int
    SPI_RECEIVE_FIELD_NUMBER: _builtins.int
    SPI_TRANSMIT_FIELD_NUMBER: _builtins.int
    SPI_TRANSACTION_FIELD_NUMBER: _builtins.int
    UART_RECEIVE_FIELD_NUMBER: _builtins.int
    UART_TRANSMIT_FIELD_NUMBER: _builtins.int
    PWM_SET_FIELD_NUMBER: _builtins.int

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GPIO_READ_FIELD_NUMBER: builtins.int
    GPIO_WRITE_FIELD_NUMBER: builtins.int
    ADC_READ_FIELD_NUMBER: builtins.int
    I2C_READY_FIELD_NUMBER: builtins.int
    I2C_RECEIVE_FIELD_NUMBER: builtins.int
    I2C_TRANSMIT_FIELD_NUMBER: builtins.int
    I2C_MEMORY_READ_FIELD_NUMBER: builtins.int
    I2C_MEMORY_WRITE_FIELD_NUMBER: builtins.int
    SPI_RECEIVE_FIELD_NUMBER: builtins.int
    SPI_TRANSMIT_FIELD_NUMBER: builtins.int
    SPI_TRANSACTION_FIELD_NUMBER: builtins.int

    @property
    def gpio_read(self) -> Global___GpioReadRequest:
        """GPIO."""

    @property
    def gpio_write(self) -> Global___GpioWriteRequest: ...
    @property
    def adc_read(self) -> Global___AdcReadRequest:
        """ADC."""

    @property
    def i2c_ready(self) -> Global___I2cReadyRequest:
        """I2C."""

    @property
    def i2c_receive(self) -> Global___I2cReceiveRequest: ...
    @property
    def i2c_transmit(self) -> Global___I2cTransmitRequest: ...
    @property
    def i2c_memory_read(self) -> Global___I2cMemoryReadRequest: ...
    @property
    def i2c_memory_write(self) -> Global___I2cMemoryWriteRequest: ...
    @property
    def spi_receive(self) -> Global___SpiReceiveRequest:
        """SPI."""

    @property
    def spi_transmit(self) -> Global___SpiTransmitRequest: ...
    @property
    def spi_transaction(self) -> Global___SpiTransactionRequest: ...
    def __init__(
        self,
        *,
        gpio_read: Global___GpioReadRequest | None = ...,
        gpio_write: Global___GpioWriteRequest | None = ...,
        adc_read: Global___AdcReadRequest | None = ...,
        i2c_ready: Global___I2cReadyRequest | None = ...,
        i2c_receive: Global___I2cReceiveRequest | None = ...,
        i2c_transmit: Global___I2cTransmitRequest | None = ...,
        i2c_memory_read: Global___I2cMemoryReadRequest | None = ...,
        i2c_memory_write: Global___I2cMemoryWriteRequest | None = ...,
        spi_receive: Global___SpiReceiveRequest | None = ...,
        spi_transmit: Global___SpiTransmitRequest | None = ...,
        spi_transaction: Global___SpiTransactionRequest | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "adc_read",
            b"adc_read",
            "gpio_read",
            b"gpio_read",
            "gpio_write",
            b"gpio_write",
            "i2c_memory_read",
            b"i2c_memory_read",
            "i2c_memory_write",
            b"i2c_memory_write",
            "i2c_ready",
            b"i2c_ready",
            "i2c_receive",
            b"i2c_receive",
            "i2c_transmit",
            b"i2c_transmit",
            "payload",
            b"payload",
            "spi_receive",
            b"spi_receive",
            "spi_transaction",
            b"spi_transaction",
            "spi_transmit",
            b"spi_transmit",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "adc_read",
            b"adc_read",
            "gpio_read",
            b"gpio_read",
            "gpio_write",
            b"gpio_write",
            "i2c_memory_read",
            b"i2c_memory_read",
            "i2c_memory_write",
            b"i2c_memory_write",
            "i2c_ready",
            b"i2c_ready",
            "i2c_receive",
            b"i2c_receive",
            "i2c_transmit",
            b"i2c_transmit",
            "payload",
            b"payload",
            "spi_receive",
            b"spi_receive",
            "spi_transaction",
            b"spi_transaction",
            "spi_transmit",
            b"spi_transmit",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["payload", b"payload"]
    ) -> (
        typing.Literal[
            "gpio_read",
            "gpio_write",
            "adc_read",
            "i2c_ready",
            "i2c_receive",
            "i2c_transmit",
            "i2c_memory_read",
            "i2c_memory_write",
            "spi_receive",
            "spi_transmit",
            "spi_transaction",
        ]
        | None
    ): ...

Global___ChimeraV2Request: typing_extensions.TypeAlias = ChimeraV2Request

    @_builtins.property
    def uart_receive(self) -> Global___UartRecieveRequest:
        """UART."""

    @_builtins.property
    def uart_transmit(self) -> Global___UartTransmitRequest:
        ...

    @_builtins.property
    def pwm_set(self) -> Global___PwmSetRequest:
        """PWM"""

    def __init__(self, *, gpio_read: Global___GpioReadRequest | None=..., gpio_write: Global___GpioWriteRequest | None=..., adc_read: Global___AdcReadRequest | None=..., i2c_ready: Global___I2cReadyRequest | None=..., i2c_receive: Global___I2cReceiveRequest | None=..., i2c_transmit: Global___I2cTransmitRequest | None=..., i2c_memory_read: Global___I2cMemoryReadRequest | None=..., i2c_memory_write: Global___I2cMemoryWriteRequest | None=..., spi_receive: Global___SpiReceiveRequest | None=..., spi_transmit: Global___SpiTransmitRequest | None=..., spi_transaction: Global___SpiTransactionRequest | None=..., uart_receive: Global___UartRecieveRequest | None=..., uart_transmit: Global___UartTransmitRequest | None=..., pwm_set: Global___PwmSetRequest | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['adc_read', b'adc_read', 'gpio_read', b'gpio_read', 'gpio_write', b'gpio_write', 'i2c_memory_read', b'i2c_memory_read', 'i2c_memory_write', b'i2c_memory_write', 'i2c_ready', b'i2c_ready', 'i2c_receive', b'i2c_receive', 'i2c_transmit', b'i2c_transmit', 'payload', b'payload', 'pwm_set', b'pwm_set', 'spi_receive', b'spi_receive', 'spi_transaction', b'spi_transaction', 'spi_transmit', b'spi_transmit', 'uart_receive', b'uart_receive', 'uart_transmit', b'uart_transmit']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['adc_read', b'adc_read', 'gpio_read', b'gpio_read', 'gpio_write', b'gpio_write', 'i2c_memory_read', b'i2c_memory_read', 'i2c_memory_write', b'i2c_memory_write', 'i2c_ready', b'i2c_ready', 'i2c_receive', b'i2c_receive', 'i2c_transmit', b'i2c_transmit', 'payload', b'payload', 'pwm_set', b'pwm_set', 'spi_receive', b'spi_receive', 'spi_transaction', b'spi_transaction', 'spi_transmit', b'spi_transmit', 'uart_receive', b'uart_receive', 'uart_transmit', b'uart_transmit']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal['gpio_read', 'gpio_write', 'adc_read', 'i2c_ready', 'i2c_receive', 'i2c_transmit', 'i2c_memory_read', 'i2c_memory_write', 'spi_receive', 'spi_transmit', 'spi_transaction', 'uart_receive', 'uart_transmit', 'pwm_set']
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal['payload', b'payload']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None:
        ...
Global___ChimeraV2Request: _TypeAlias = ChimeraV2Request

@_typing.final
class ChimeraV2Response(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    GPIO_READ_FIELD_NUMBER: _builtins.int
    GPIO_WRITE_FIELD_NUMBER: _builtins.int
    ADC_READ_FIELD_NUMBER: _builtins.int
    I2C_READY_FIELD_NUMBER: _builtins.int
    I2C_RECEIVE_FIELD_NUMBER: _builtins.int
    I2C_TRANSMIT_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_READ_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_WRITE_FIELD_NUMBER: _builtins.int
    SPI_RECEIVE_FIELD_NUMBER: _builtins.int
    SPI_TRANSMIT_FIELD_NUMBER: _builtins.int
    SPI_TRANSACTION_FIELD_NUMBER: _builtins.int
    UART_RECEIVE_FIELD_NUMBER: _builtins.int
    UART_TRANSMIT_FIELD_NUMBER: _builtins.int
    PWM_SET_FIELD_NUMBER: _builtins.int

    @_builtins.property
    def gpio_read(self) -> Global___GpioReadResponse:
        """GPIO."""

    @property
    def gpio_write(self) -> Global___GpioWriteResponse: ...
    @property
    def adc_read(self) -> Global___AdcReadResponse:
        """ADC."""

    @property
    def i2c_ready(self) -> Global___I2cReadyResponse:
        """I2C."""

    @property
    def i2c_receive(self) -> Global___I2cReceiveResponse: ...
    @property
    def i2c_transmit(self) -> Global___I2cTransmitResponse: ...
    @property
    def i2c_memory_read(self) -> Global___I2cMemoryReadResponse: ...
    @property
    def i2c_memory_write(self) -> Global___I2cMemoryWriteResponse: ...
    @property
    def spi_receive(self) -> Global___SpiReceiveResponse:
        """SPI."""

    @property
    def spi_transmit(self) -> Global___SpiTransmitResponse: ...
    @property
    def spi_transaction(self) -> Global___SpiTransactionResponse: ...
    def __init__(
        self,
        *,
        gpio_read: Global___GpioReadResponse | None = ...,
        gpio_write: Global___GpioWriteResponse | None = ...,
        adc_read: Global___AdcReadResponse | None = ...,
        i2c_ready: Global___I2cReadyResponse | None = ...,
        i2c_receive: Global___I2cReceiveResponse | None = ...,
        i2c_transmit: Global___I2cTransmitResponse | None = ...,
        i2c_memory_read: Global___I2cMemoryReadResponse | None = ...,
        i2c_memory_write: Global___I2cMemoryWriteResponse | None = ...,
        spi_receive: Global___SpiReceiveResponse | None = ...,
        spi_transmit: Global___SpiTransmitResponse | None = ...,
        spi_transaction: Global___SpiTransactionResponse | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "adc_read",
            b"adc_read",
            "gpio_read",
            b"gpio_read",
            "gpio_write",
            b"gpio_write",
            "i2c_memory_read",
            b"i2c_memory_read",
            "i2c_memory_write",
            b"i2c_memory_write",
            "i2c_ready",
            b"i2c_ready",
            "i2c_receive",
            b"i2c_receive",
            "i2c_transmit",
            b"i2c_transmit",
            "payload",
            b"payload",
            "spi_receive",
            b"spi_receive",
            "spi_transaction",
            b"spi_transaction",
            "spi_transmit",
            b"spi_transmit",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "adc_read",
            b"adc_read",
            "gpio_read",
            b"gpio_read",
            "gpio_write",
            b"gpio_write",
            "i2c_memory_read",
            b"i2c_memory_read",
            "i2c_memory_write",
            b"i2c_memory_write",
            "i2c_ready",
            b"i2c_ready",
            "i2c_receive",
            b"i2c_receive",
            "i2c_transmit",
            b"i2c_transmit",
            "payload",
            b"payload",
            "spi_receive",
            b"spi_receive",
            "spi_transaction",
            b"spi_transaction",
            "spi_transmit",
            b"spi_transmit",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["payload", b"payload"]
    ) -> (
        typing.Literal[
            "gpio_read",
            "gpio_write",
            "adc_read",
            "i2c_ready",
            "i2c_receive",
            "i2c_transmit",
            "i2c_memory_read",
            "i2c_memory_write",
            "spi_receive",
            "spi_transmit",
            "spi_transaction",
        ]
        | None
    ): ...

    @_builtins.property
    def spi_transaction(self) -> Global___SpiTransactionResponse:
        ...

    @_builtins.property
    def uart_receive(self) -> Global___UartReceiveResponse:
        """UART."""

    @_builtins.property
    def uart_transmit(self) -> Global___UartTransmitResponse:
        ...

    @_builtins.property
    def pwm_set(self) -> Global___PwmSetResponse:
        """PWM"""

    def __init__(self, *, gpio_read: Global___GpioReadResponse | None=..., gpio_write: Global___GpioWriteResponse | None=..., adc_read: Global___AdcReadResponse | None=..., i2c_ready: Global___I2cReadyResponse | None=..., i2c_receive: Global___I2cReceiveResponse | None=..., i2c_transmit: Global___I2cTransmitResponse | None=..., i2c_memory_read: Global___I2cMemoryReadResponse | None=..., i2c_memory_write: Global___I2cMemoryWriteResponse | None=..., spi_receive: Global___SpiReceiveResponse | None=..., spi_transmit: Global___SpiTransmitResponse | None=..., spi_transaction: Global___SpiTransactionResponse | None=..., uart_receive: Global___UartReceiveResponse | None=..., uart_transmit: Global___UartTransmitResponse | None=..., pwm_set: Global___PwmSetResponse | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['adc_read', b'adc_read', 'gpio_read', b'gpio_read', 'gpio_write', b'gpio_write', 'i2c_memory_read', b'i2c_memory_read', 'i2c_memory_write', b'i2c_memory_write', 'i2c_ready', b'i2c_ready', 'i2c_receive', b'i2c_receive', 'i2c_transmit', b'i2c_transmit', 'payload', b'payload', 'pwm_set', b'pwm_set', 'spi_receive', b'spi_receive', 'spi_transaction', b'spi_transaction', 'spi_transmit', b'spi_transmit', 'uart_receive', b'uart_receive', 'uart_transmit', b'uart_transmit']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['adc_read', b'adc_read', 'gpio_read', b'gpio_read', 'gpio_write', b'gpio_write', 'i2c_memory_read', b'i2c_memory_read', 'i2c_memory_write', b'i2c_memory_write', 'i2c_ready', b'i2c_ready', 'i2c_receive', b'i2c_receive', 'i2c_transmit', b'i2c_transmit', 'payload', b'payload', 'pwm_set', b'pwm_set', 'spi_receive', b'spi_receive', 'spi_transaction', b'spi_transaction', 'spi_transmit', b'spi_transmit', 'uart_receive', b'uart_receive', 'uart_transmit', b'uart_transmit']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal['gpio_read', 'gpio_write', 'adc_read', 'i2c_ready', 'i2c_receive', 'i2c_transmit', 'i2c_memory_read', 'i2c_memory_write', 'spi_receive', 'spi_transmit', 'spi_transaction', 'uart_receive', 'uart_transmit', 'pwm_set']
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal['payload', b'payload']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None:
        ...
Global___ChimeraV2Response: _TypeAlias = ChimeraV2Response
