"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import bms_pb2 as _bms_pb2
import builtins as _builtins
import crit_pb2 as _crit_pb2
import dam_pb2 as _dam_pb2
import f4dev_pb2 as _f4dev_pb2
import fsm_pb2 as _fsm_pb2
import rsm_pb2 as _rsm_pb2
import sys
import typing as _typing
import vc_pb2 as _vc_pb2

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GpioNetName(_message.Message):
    """GPIOs"""

    DESCRIPTOR: _descriptor.Descriptor

    F4DEV_NET_NAME_FIELD_NUMBER: _builtins.int
    CRIT_NET_NAME_FIELD_NUMBER: _builtins.int
    DAM_NET_NAME_FIELD_NUMBER: _builtins.int
    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    FSM_NET_NAME_FIELD_NUMBER: _builtins.int
    BMS_NET_NAME_FIELD_NUMBER: _builtins.int
    VC_NET_NAME_FIELD_NUMBER: _builtins.int
    f4dev_net_name: _f4dev_pb2.GpioNetName.ValueType
    crit_net_name: _crit_pb2.GpioNetName.ValueType
    dam_net_name: _dam_pb2.GpioNetName.ValueType
    rsm_net_name: _rsm_pb2.GpioNetName.ValueType
    fsm_net_name: _fsm_pb2.GpioNetName.ValueType
    bms_net_name: _bms_pb2.GpioNetName.ValueType
    vc_net_name: _vc_pb2.GpioNetName.ValueType
    def __init__(
        self,
        *,
        f4dev_net_name: _f4dev_pb2.GpioNetName.ValueType = ...,
        crit_net_name: _crit_pb2.GpioNetName.ValueType = ...,
        dam_net_name: _dam_pb2.GpioNetName.ValueType = ...,
        rsm_net_name: _rsm_pb2.GpioNetName.ValueType = ...,
        fsm_net_name: _fsm_pb2.GpioNetName.ValueType = ...,
        bms_net_name: _bms_pb2.GpioNetName.ValueType = ...,
        vc_net_name: _vc_pb2.GpioNetName.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "crit_net_name", b"crit_net_name", "dam_net_name", b"dam_net_name", "f4dev_net_name", b"f4dev_net_name", "fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "crit_net_name", b"crit_net_name", "dam_net_name", b"dam_net_name", "f4dev_net_name", b"f4dev_net_name", "fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal["f4dev_net_name", "crit_net_name", "dam_net_name", "rsm_net_name", "fsm_net_name", "bms_net_name", "vc_net_name"]  # noqa: Y015
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None: ...

Global___GpioNetName: _TypeAlias = GpioNetName  # noqa: Y015

@_typing.final
class GpioReadRequest(_message.Message):
    """GPIO read request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___GpioNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___GpioNetName | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GpioReadRequest: _TypeAlias = GpioReadRequest  # noqa: Y015

@_typing.final
class GpioReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bool
    def __init__(
        self,
        *,
        value: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GpioReadResponse: _TypeAlias = GpioReadResponse  # noqa: Y015

@_typing.final
class GpioWriteRequest(_message.Message):
    """GPIO write request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bool
    @_builtins.property
    def net_name(self) -> Global___GpioNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___GpioNetName | None = ...,
        value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GpioWriteRequest: _TypeAlias = GpioWriteRequest  # noqa: Y015

@_typing.final
class GpioWriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GpioWriteResponse: _TypeAlias = GpioWriteResponse  # noqa: Y015

@_typing.final
class AdcNetName(_message.Message):
    """ADCs"""

    DESCRIPTOR: _descriptor.Descriptor

    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    FSM_NET_NAME_FIELD_NUMBER: _builtins.int
    BMS_NET_NAME_FIELD_NUMBER: _builtins.int
    VC_NET_NAME_FIELD_NUMBER: _builtins.int
    rsm_net_name: _rsm_pb2.AdcNetName.ValueType
    fsm_net_name: _fsm_pb2.AdcNetName.ValueType
    bms_net_name: _bms_pb2.AdcNetName.ValueType
    vc_net_name: _vc_pb2.AdcNetName.ValueType
    def __init__(
        self,
        *,
        rsm_net_name: _rsm_pb2.AdcNetName.ValueType = ...,
        fsm_net_name: _fsm_pb2.AdcNetName.ValueType = ...,
        bms_net_name: _bms_pb2.AdcNetName.ValueType = ...,
        vc_net_name: _vc_pb2.AdcNetName.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal["rsm_net_name", "fsm_net_name", "bms_net_name", "vc_net_name"]  # noqa: Y015
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None: ...

Global___AdcNetName: _TypeAlias = AdcNetName  # noqa: Y015

@_typing.final
class AdcReadRequest(_message.Message):
    """ADC read request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___AdcNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___AdcNetName | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdcReadRequest: _TypeAlias = AdcReadRequest  # noqa: Y015

@_typing.final
class AdcReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.float
    def __init__(
        self,
        *,
        value: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdcReadResponse: _TypeAlias = AdcReadResponse  # noqa: Y015

@_typing.final
class I2cNetName(_message.Message):
    """I2Cs"""

    DESCRIPTOR: _descriptor.Descriptor

    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    FSM_NET_NAME_FIELD_NUMBER: _builtins.int
    VC_NET_NAME_FIELD_NUMBER: _builtins.int
    rsm_net_name: _rsm_pb2.I2cNetName.ValueType
    fsm_net_name: _fsm_pb2.I2cNetName.ValueType
    vc_net_name: _vc_pb2.I2cNetName.ValueType
    def __init__(
        self,
        *,
        rsm_net_name: _rsm_pb2.I2cNetName.ValueType = ...,
        fsm_net_name: _fsm_pb2.I2cNetName.ValueType = ...,
        vc_net_name: _vc_pb2.I2cNetName.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fsm_net_name", b"fsm_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name", "vc_net_name", b"vc_net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal["rsm_net_name", "fsm_net_name", "vc_net_name"]  # noqa: Y015
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None: ...

Global___I2cNetName: _TypeAlias = I2cNetName  # noqa: Y015

@_typing.final
class I2cReadyRequest(_message.Message):
    """I2C ready check request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cReadyRequest: _TypeAlias = I2cReadyRequest  # noqa: Y015

@_typing.final
class I2cReadyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    READY_FIELD_NUMBER: _builtins.int
    ready: _builtins.bool
    def __init__(
        self,
        *,
        ready: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ready", b"ready"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cReadyResponse: _TypeAlias = I2cReadyResponse  # noqa: Y015

@_typing.final
class I2cReceiveRequest(_message.Message):
    """I2C receive data request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    length: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length", b"length", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cReceiveRequest: _TypeAlias = I2cReceiveRequest  # noqa: Y015

@_typing.final
class I2cReceiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cReceiveResponse: _TypeAlias = I2cReceiveResponse  # noqa: Y015

@_typing.final
class I2cTransmitRequest(_message.Message):
    """I2C transmit data request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cTransmitRequest: _TypeAlias = I2cTransmitRequest  # noqa: Y015

@_typing.final
class I2cTransmitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cTransmitResponse: _TypeAlias = I2cTransmitResponse  # noqa: Y015

@_typing.final
class I2cMemoryReadRequest(_message.Message):
    """I2C read memory request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    MEMORY_ADDRESS_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    memory_address: _builtins.int
    length: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        memory_address: _builtins.int = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length", b"length", "memory_address", b"memory_address", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cMemoryReadRequest: _TypeAlias = I2cMemoryReadRequest  # noqa: Y015

@_typing.final
class I2cMemoryReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cMemoryReadResponse: _TypeAlias = I2cMemoryReadResponse  # noqa: Y015

@_typing.final
class I2cMemoryWriteRequest(_message.Message):
    """I2C write memory request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    MEMORY_ADDRESS_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    memory_address: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def net_name(self) -> Global___I2cNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___I2cNetName | None = ...,
        memory_address: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "memory_address", b"memory_address", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cMemoryWriteRequest: _TypeAlias = I2cMemoryWriteRequest  # noqa: Y015

@_typing.final
class I2cMemoryWriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___I2cMemoryWriteResponse: _TypeAlias = I2cMemoryWriteResponse  # noqa: Y015

@_typing.final
class SpiNetName(_message.Message):
    """SPIs"""

    DESCRIPTOR: _descriptor.Descriptor

    BMS_NET_NAME_FIELD_NUMBER: _builtins.int
    CRIT_NET_NAME_FIELD_NUMBER: _builtins.int
    RSM_NET_NAME_FIELD_NUMBER: _builtins.int
    bms_net_name: _bms_pb2.SpiNetName.ValueType
    crit_net_name: _crit_pb2.SpiNetName.ValueType
    rsm_net_name: _rsm_pb2.SpiNetName.ValueType
    def __init__(
        self,
        *,
        bms_net_name: _bms_pb2.SpiNetName.ValueType = ...,
        crit_net_name: _crit_pb2.SpiNetName.ValueType = ...,
        rsm_net_name: _rsm_pb2.SpiNetName.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "crit_net_name", b"crit_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bms_net_name", b"bms_net_name", "crit_net_name", b"crit_net_name", "name", b"name", "rsm_net_name", b"rsm_net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_name: _TypeAlias = _typing.Literal["bms_net_name", "crit_net_name", "rsm_net_name"]  # noqa: Y015
    _WhichOneofArgType_name: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_name) -> _WhichOneofReturnType_name | None: ...

Global___SpiNetName: _TypeAlias = SpiNetName  # noqa: Y015

@_typing.final
class SpiTransmitRequest(_message.Message):
    """SPI transmit data request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___SpiNetName | None = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiTransmitRequest: _TypeAlias = SpiTransmitRequest  # noqa: Y015

@_typing.final
class SpiTransmitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiTransmitResponse: _TypeAlias = SpiTransmitResponse  # noqa: Y015

@_typing.final
class SpiReceiveRequest(_message.Message):
    """SPI receive data request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    length: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___SpiNetName | None = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length", b"length", "net_name", b"net_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiReceiveRequest: _TypeAlias = SpiReceiveRequest  # noqa: Y015

@_typing.final
class SpiReceiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiReceiveResponse: _TypeAlias = SpiReceiveResponse  # noqa: Y015

@_typing.final
class SpiTransactionRequest(_message.Message):
    """SPI full-duplex request/response."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_NAME_FIELD_NUMBER: _builtins.int
    TX_DATA_FIELD_NUMBER: _builtins.int
    RX_LENGTH_FIELD_NUMBER: _builtins.int
    tx_data: _builtins.bytes
    rx_length: _builtins.int
    @_builtins.property
    def net_name(self) -> Global___SpiNetName: ...
    def __init__(
        self,
        *,
        net_name: Global___SpiNetName | None = ...,
        tx_data: _builtins.bytes = ...,
        rx_length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net_name", b"net_name", "rx_length", b"rx_length", "tx_data", b"tx_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiTransactionRequest: _TypeAlias = SpiTransactionRequest  # noqa: Y015

@_typing.final
class SpiTransactionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RX_DATA_FIELD_NUMBER: _builtins.int
    rx_data: _builtins.bytes
    def __init__(
        self,
        *,
        rx_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rx_data", b"rx_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpiTransactionResponse: _TypeAlias = SpiTransactionResponse  # noqa: Y015

@_typing.final
class ChimeraV2Request(_message.Message):
    """
    Wrapper around all messages 

    There is no RPC support in nanopb, so we construct our own request/response protocol.
    Some interesting projects to like at in the future if this ever gets too cumbersome are:
    - https://github.com/EmbeddedRPC/erpc
    - https://github.com/d21d3q/nanogrpc
    """

    DESCRIPTOR: _descriptor.Descriptor

    GPIO_READ_FIELD_NUMBER: _builtins.int
    GPIO_WRITE_FIELD_NUMBER: _builtins.int
    ADC_READ_FIELD_NUMBER: _builtins.int
    I2C_READY_FIELD_NUMBER: _builtins.int
    I2C_RECEIVE_FIELD_NUMBER: _builtins.int
    I2C_TRANSMIT_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_READ_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_WRITE_FIELD_NUMBER: _builtins.int
    SPI_RECEIVE_FIELD_NUMBER: _builtins.int
    SPI_TRANSMIT_FIELD_NUMBER: _builtins.int
    SPI_TRANSACTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gpio_read(self) -> Global___GpioReadRequest:
        """GPIO."""

    @_builtins.property
    def gpio_write(self) -> Global___GpioWriteRequest: ...
    @_builtins.property
    def adc_read(self) -> Global___AdcReadRequest:
        """ADC."""

    @_builtins.property
    def i2c_ready(self) -> Global___I2cReadyRequest:
        """I2C."""

    @_builtins.property
    def i2c_receive(self) -> Global___I2cReceiveRequest: ...
    @_builtins.property
    def i2c_transmit(self) -> Global___I2cTransmitRequest: ...
    @_builtins.property
    def i2c_memory_read(self) -> Global___I2cMemoryReadRequest: ...
    @_builtins.property
    def i2c_memory_write(self) -> Global___I2cMemoryWriteRequest: ...
    @_builtins.property
    def spi_receive(self) -> Global___SpiReceiveRequest:
        """SPI."""

    @_builtins.property
    def spi_transmit(self) -> Global___SpiTransmitRequest: ...
    @_builtins.property
    def spi_transaction(self) -> Global___SpiTransactionRequest: ...
    def __init__(
        self,
        *,
        gpio_read: Global___GpioReadRequest | None = ...,
        gpio_write: Global___GpioWriteRequest | None = ...,
        adc_read: Global___AdcReadRequest | None = ...,
        i2c_ready: Global___I2cReadyRequest | None = ...,
        i2c_receive: Global___I2cReceiveRequest | None = ...,
        i2c_transmit: Global___I2cTransmitRequest | None = ...,
        i2c_memory_read: Global___I2cMemoryReadRequest | None = ...,
        i2c_memory_write: Global___I2cMemoryWriteRequest | None = ...,
        spi_receive: Global___SpiReceiveRequest | None = ...,
        spi_transmit: Global___SpiTransmitRequest | None = ...,
        spi_transaction: Global___SpiTransactionRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adc_read", b"adc_read", "gpio_read", b"gpio_read", "gpio_write", b"gpio_write", "i2c_memory_read", b"i2c_memory_read", "i2c_memory_write", b"i2c_memory_write", "i2c_ready", b"i2c_ready", "i2c_receive", b"i2c_receive", "i2c_transmit", b"i2c_transmit", "payload", b"payload", "spi_receive", b"spi_receive", "spi_transaction", b"spi_transaction", "spi_transmit", b"spi_transmit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adc_read", b"adc_read", "gpio_read", b"gpio_read", "gpio_write", b"gpio_write", "i2c_memory_read", b"i2c_memory_read", "i2c_memory_write", b"i2c_memory_write", "i2c_ready", b"i2c_ready", "i2c_receive", b"i2c_receive", "i2c_transmit", b"i2c_transmit", "payload", b"payload", "spi_receive", b"spi_receive", "spi_transaction", b"spi_transaction", "spi_transmit", b"spi_transmit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["gpio_read", "gpio_write", "adc_read", "i2c_ready", "i2c_receive", "i2c_transmit", "i2c_memory_read", "i2c_memory_write", "spi_receive", "spi_transmit", "spi_transaction"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ChimeraV2Request: _TypeAlias = ChimeraV2Request  # noqa: Y015

@_typing.final
class ChimeraV2Response(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GPIO_READ_FIELD_NUMBER: _builtins.int
    GPIO_WRITE_FIELD_NUMBER: _builtins.int
    ADC_READ_FIELD_NUMBER: _builtins.int
    I2C_READY_FIELD_NUMBER: _builtins.int
    I2C_RECEIVE_FIELD_NUMBER: _builtins.int
    I2C_TRANSMIT_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_READ_FIELD_NUMBER: _builtins.int
    I2C_MEMORY_WRITE_FIELD_NUMBER: _builtins.int
    SPI_RECEIVE_FIELD_NUMBER: _builtins.int
    SPI_TRANSMIT_FIELD_NUMBER: _builtins.int
    SPI_TRANSACTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gpio_read(self) -> Global___GpioReadResponse:
        """GPIO."""

    @_builtins.property
    def gpio_write(self) -> Global___GpioWriteResponse: ...
    @_builtins.property
    def adc_read(self) -> Global___AdcReadResponse:
        """ADC."""

    @_builtins.property
    def i2c_ready(self) -> Global___I2cReadyResponse:
        """I2C."""

    @_builtins.property
    def i2c_receive(self) -> Global___I2cReceiveResponse: ...
    @_builtins.property
    def i2c_transmit(self) -> Global___I2cTransmitResponse: ...
    @_builtins.property
    def i2c_memory_read(self) -> Global___I2cMemoryReadResponse: ...
    @_builtins.property
    def i2c_memory_write(self) -> Global___I2cMemoryWriteResponse: ...
    @_builtins.property
    def spi_receive(self) -> Global___SpiReceiveResponse:
        """SPI."""

    @_builtins.property
    def spi_transmit(self) -> Global___SpiTransmitResponse: ...
    @_builtins.property
    def spi_transaction(self) -> Global___SpiTransactionResponse: ...
    def __init__(
        self,
        *,
        gpio_read: Global___GpioReadResponse | None = ...,
        gpio_write: Global___GpioWriteResponse | None = ...,
        adc_read: Global___AdcReadResponse | None = ...,
        i2c_ready: Global___I2cReadyResponse | None = ...,
        i2c_receive: Global___I2cReceiveResponse | None = ...,
        i2c_transmit: Global___I2cTransmitResponse | None = ...,
        i2c_memory_read: Global___I2cMemoryReadResponse | None = ...,
        i2c_memory_write: Global___I2cMemoryWriteResponse | None = ...,
        spi_receive: Global___SpiReceiveResponse | None = ...,
        spi_transmit: Global___SpiTransmitResponse | None = ...,
        spi_transaction: Global___SpiTransactionResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adc_read", b"adc_read", "gpio_read", b"gpio_read", "gpio_write", b"gpio_write", "i2c_memory_read", b"i2c_memory_read", "i2c_memory_write", b"i2c_memory_write", "i2c_ready", b"i2c_ready", "i2c_receive", b"i2c_receive", "i2c_transmit", b"i2c_transmit", "payload", b"payload", "spi_receive", b"spi_receive", "spi_transaction", b"spi_transaction", "spi_transmit", b"spi_transmit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adc_read", b"adc_read", "gpio_read", b"gpio_read", "gpio_write", b"gpio_write", "i2c_memory_read", b"i2c_memory_read", "i2c_memory_write", b"i2c_memory_write", "i2c_ready", b"i2c_ready", "i2c_receive", b"i2c_receive", "i2c_transmit", b"i2c_transmit", "payload", b"payload", "spi_receive", b"spi_receive", "spi_transaction", b"spi_transaction", "spi_transmit", b"spi_transmit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["gpio_read", "gpio_write", "adc_read", "i2c_ready", "i2c_receive", "i2c_transmit", "i2c_memory_read", "i2c_memory_write", "spi_receive", "spi_transmit", "spi_transaction"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ChimeraV2Response: _TypeAlias = ChimeraV2Response  # noqa: Y015
