"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

class _GpioNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_F_INV_EN: _GpioNetName.ValueType
    GPIO_F_INV_PG: _GpioNetName.ValueType
    GPIO_R_INV_EN: _GpioNetName.ValueType
    GPIO_R_INV_PG: _GpioNetName.ValueType
    GPIO_DAM_EN: _GpioNetName.ValueType
    GPIO_DAM_PG: _GpioNetName.ValueType
    GPIO_BMS_EN: _GpioNetName.ValueType
    GPIO_BMS_PG: _GpioNetName.ValueType
    GPIO_BOOST_PG: _GpioNetName.ValueType
    GPIO_RSM_EN: _GpioNetName.ValueType
    GPIO_RSM_PG: _GpioNetName.ValueType
    GPIO_RR_PUMP_EN: _GpioNetName.ValueType
    GPIO_RR_PUMP_PGOOD: _GpioNetName.ValueType
    GPIO_RL_PUMP_EN: _GpioNetName.ValueType
    GPIO_RL_PUMP_PGOOD: _GpioNetName.ValueType
    GPIO_PCM_EN: _GpioNetName.ValueType
    GPIO_L_RAD_FAN_EN: _GpioNetName.ValueType
    GPIO_L_RAD_FAN_PG: _GpioNetName.ValueType
    GPIO_R_RAD_FAN_EN: _GpioNetName.ValueType
    GPIO_R_RAD_FAN_PG: _GpioNetName.ValueType
    GPIO_FRONT_EN: _GpioNetName.ValueType
    GPIO_FRONT_PG: _GpioNetName.ValueType
    GPIO_SB_SHDN_3V3_OUT: _GpioNetName.ValueType
    GPIO_BAT_CHRG_MODE: _GpioNetName.ValueType
    GPIO_BAT_CHRG_nSHDN: _GpioNetName.ValueType
    GPIO_IMU_FSYNC: _GpioNetName.ValueType
    GPIO_PWR_MTR_nALERT: _GpioNetName.ValueType
    GPIO_BOOT: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_RR_ILCK_3V3_OUT: _GpioNetName.ValueType
    GPIO_TSMS_3V3_OUT: _GpioNetName.ValueType
    GPIO_IMU_CS1: _GpioNetName.ValueType
    GPIO_IMU_CS2: _GpioNetName.ValueType
    GPIO_IMU_CS3: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_F_INV_EN: GpioNetName.ValueType
GPIO_F_INV_PG: GpioNetName.ValueType
GPIO_R_INV_EN: GpioNetName.ValueType
GPIO_R_INV_PG: GpioNetName.ValueType
GPIO_DAM_EN: GpioNetName.ValueType
GPIO_DAM_PG: GpioNetName.ValueType
GPIO_BMS_EN: GpioNetName.ValueType
GPIO_BMS_PG: GpioNetName.ValueType
GPIO_BOOST_PG: GpioNetName.ValueType
GPIO_RSM_EN: GpioNetName.ValueType
GPIO_RSM_PG: GpioNetName.ValueType
GPIO_RR_PUMP_EN: GpioNetName.ValueType
GPIO_RR_PUMP_PGOOD: GpioNetName.ValueType
GPIO_RL_PUMP_EN: GpioNetName.ValueType
GPIO_RL_PUMP_PGOOD: GpioNetName.ValueType
GPIO_PCM_EN: GpioNetName.ValueType
GPIO_L_RAD_FAN_EN: GpioNetName.ValueType
GPIO_L_RAD_FAN_PG: GpioNetName.ValueType
GPIO_R_RAD_FAN_EN: GpioNetName.ValueType
GPIO_R_RAD_FAN_PG: GpioNetName.ValueType
GPIO_FRONT_EN: GpioNetName.ValueType
GPIO_FRONT_PG: GpioNetName.ValueType
GPIO_SB_SHDN_3V3_OUT: GpioNetName.ValueType
GPIO_BAT_CHRG_MODE: GpioNetName.ValueType
GPIO_BAT_CHRG_nSHDN: GpioNetName.ValueType
GPIO_IMU_FSYNC: GpioNetName.ValueType
GPIO_PWR_MTR_nALERT: GpioNetName.ValueType
GPIO_BOOT: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_RR_ILCK_3V3_OUT: GpioNetName.ValueType
GPIO_TSMS_3V3_OUT: GpioNetName.ValueType
GPIO_IMU_CS1: GpioNetName.ValueType
GPIO_IMU_CS2: GpioNetName.ValueType
GPIO_IMU_CS3: GpioNetName.ValueType
Global___GpioNetName: _TypeAlias = GpioNetName

class _AdcNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_RR_PUMP: _AdcNetName.ValueType
    ADC_DAM: _AdcNetName.ValueType
    ADC_L_RAD_FAN: _AdcNetName.ValueType
    ADC_R_RAD_FAN: _AdcNetName.ValueType
    ADC_RL_PUMP: _AdcNetName.ValueType
    ADC_F_INV: _AdcNetName.ValueType
    ADC_R_INV: _AdcNetName.ValueType
    ADC_BMS: _AdcNetName.ValueType
    ADC_FRONT: _AdcNetName.ValueType
    ADC_RSM: _AdcNetName.ValueType
    ADC_MISC_FUSE: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_RR_PUMP: AdcNetName.ValueType
ADC_DAM: AdcNetName.ValueType
ADC_L_RAD_FAN: AdcNetName.ValueType
ADC_R_RAD_FAN: AdcNetName.ValueType
ADC_RL_PUMP: AdcNetName.ValueType
ADC_F_INV: AdcNetName.ValueType
ADC_R_INV: AdcNetName.ValueType
ADC_BMS: AdcNetName.ValueType
ADC_FRONT: AdcNetName.ValueType
ADC_RSM: AdcNetName.ValueType
ADC_MISC_FUSE: AdcNetName.ValueType
Global___AdcNetName: _TypeAlias = AdcNetName

class _I2cNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _I2cNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_I2cNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    I2C_NET_NAME_UNSPECIFIED: _I2cNetName.ValueType
    I2C_BAT_MON: _I2cNetName.ValueType
    I2C_PWR_PUMP: _I2cNetName.ValueType

class I2cNetName(_I2cNetName, metaclass=_I2cNetNameEnumTypeWrapper):
    ...
I2C_NET_NAME_UNSPECIFIED: I2cNetName.ValueType
I2C_BAT_MON: I2cNetName.ValueType
I2C_PWR_PUMP: I2cNetName.ValueType
Global___I2cNetName: _TypeAlias = I2cNetName

class _SpiNetName:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    IMU1: _SpiNetName.ValueType
    IMU2: _SpiNetName.ValueType
    IMU3: _SpiNetName.ValueType
    RPI: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
IMU1: SpiNetName.ValueType
IMU2: SpiNetName.ValueType
IMU3: SpiNetName.ValueType
RPI: SpiNetName.ValueType
Global___SpiNetName: _TypeAlias = SpiNetName