#ifndef APP_WORLD_H_
#define APP_WORLD_H_

#include "App_Adc.h"
#include "App_Gpio.h"
// I assume this exists and creates a `App_Can_Interface`. It would need 
// to live in the autogenerated code
// TODO: this should be split into CanRx and CanTx interfaces
#include "App_Can.h"

// TODO: need to rename to `App_World_Interface`
struct World_Interface;

World_Interface *App_World_Alloc(
    App_Can_Interface * can_interface,
    App_Adc_Interface * adc_interface,
    App_Gpio_interface *gpio_interface);

App_Can_Interface * App_World_GetCanInterface(World_Interface *world);
App_Adc_Interface * App_World_GetAdcInterface(World_Interface *world);
App_Gpio_Interface *App_World_GetGpioInterface(World_Interface *world);

#endif /* APP_WORLD_H_ */
