#ifndef FORMULA_ELECTRIC_FIRMWARE_APP_PDMCONSTS_H
#define FORMULA_ELECTRIC_FIRMWARE_APP_PDMCONSTS_H

#endif //FORMULA_ELECTRIC_FIRMWARE_APP_PDMCONSTS_H

#define PDM_LOADSWITCH_VOLTAGES \
    PDM_LOADSWITCH_MAX_SUPPLYVOLTAGE, \
    PDM_LOADSWITCH_MIN_SUPPLY_VOLTAGE, \
    PDM_LOADSWITCH_MAX_CURRENTSENSE_VOLTAGE, \
    PDM_LOADSWITCH_HIGH_FR_STDBY_FAULT_VOLTAGE, \
    PDM_LOADSWITCH_LOW_FR_STDBY_FAULT_VOLTAGE, \
