"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    TELEM_PWR_EN: _GpioNetName.ValueType
    BUZZER_PWR_EN: _GpioNetName.ValueType
    TSIM_RED_EN: _GpioNetName.ValueType
    NTSIM_GRN_EN: _GpioNetName.ValueType
    R_SHDN_SENSE: _GpioNetName.ValueType
    L_SHDN_SENSE: _GpioNetName.ValueType
    LED: _GpioNetName.ValueType
    BOOT: _GpioNetName.ValueType
    SD_PRESENT: _GpioNetName.ValueType
    N_RTC_INT1: _GpioNetName.ValueType
    _900M: _GpioNetName.ValueType
    SD_FAIL: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
TELEM_PWR_EN: GpioNetName.ValueType
BUZZER_PWR_EN: GpioNetName.ValueType
TSIM_RED_EN: GpioNetName.ValueType
NTSIM_GRN_EN: GpioNetName.ValueType
R_SHDN_SENSE: GpioNetName.ValueType
L_SHDN_SENSE: GpioNetName.ValueType
LED: GpioNetName.ValueType
BOOT: GpioNetName.ValueType
SD_PRESENT: GpioNetName.ValueType
N_RTC_INT1: GpioNetName.ValueType
_900M: GpioNetName.ValueType
SD_FAIL: GpioNetName.ValueType
global___GpioNetName = GpioNetName

class _AdcNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
global___AdcNetName = AdcNetName

class _I2cNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _I2cNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_I2cNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    I2C_NET_NAME_UNSPECIFIED: _I2cNetName.ValueType
    RTC_I2C: _I2cNetName.ValueType

class I2cNetName(_I2cNetName, metaclass=_I2cNetNameEnumTypeWrapper):
    ...
I2C_NET_NAME_UNSPECIFIED: I2cNetName.ValueType
RTC_I2C: I2cNetName.ValueType
global___I2cNetName = I2cNetName