"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
global___GpioNetName = GpioNetName