"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_LED: _GpioNetName.ValueType
    GPIO_BRAKE_LIGHT_EN: _GpioNetName.ValueType
    GPIO_RL_INT: _GpioNetName.ValueType
    GPIO_IMU_INT1: _GpioNetName.ValueType
    GPIO_IMU_INT2: _GpioNetName.ValueType
    GPIO_BOOT: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RR_OCSC: _GpioNetName.ValueType
    GPIO_SUSP_TRAVEL_RL_OCSC: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_LED: GpioNetName.ValueType
GPIO_BRAKE_LIGHT_EN: GpioNetName.ValueType
GPIO_RL_INT: GpioNetName.ValueType
GPIO_IMU_INT1: GpioNetName.ValueType
GPIO_IMU_INT2: GpioNetName.ValueType
GPIO_BOOT: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RR_OCSC: GpioNetName.ValueType
GPIO_SUSP_TRAVEL_RL_OCSC: GpioNetName.ValueType
global___GpioNetName = GpioNetName

class _AdcNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AdcNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AdcNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADC_NET_NAME_UNSPECIFIED: _AdcNetName.ValueType
    ADC_LC3_OUT: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RL_3V3: _AdcNetName.ValueType
    ADC_SUSP_TRAVEL_RR_3V3: _AdcNetName.ValueType
    ADC_BPS_3V3: _AdcNetName.ValueType

class AdcNetName(_AdcNetName, metaclass=_AdcNetNameEnumTypeWrapper):
    ...
ADC_NET_NAME_UNSPECIFIED: AdcNetName.ValueType
ADC_LC3_OUT: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RL_3V3: AdcNetName.ValueType
ADC_SUSP_TRAVEL_RR_3V3: AdcNetName.ValueType
ADC_BPS_3V3: AdcNetName.ValueType
global___AdcNetName = AdcNetName

class _I2cNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _I2cNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_I2cNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    I2C_NET_NAME_UNSPECIFIED: _I2cNetName.ValueType
    I2C_IMU_I2C: _I2cNetName.ValueType
    I2C_R_PUMP_I2C: _I2cNetName.ValueType

class I2cNetName(_I2cNetName, metaclass=_I2cNetNameEnumTypeWrapper):
    ...
I2C_NET_NAME_UNSPECIFIED: I2cNetName.ValueType
I2C_IMU_I2C: I2cNetName.ValueType
I2C_R_PUMP_I2C: I2cNetName.ValueType
global___I2cNetName = I2cNetName

class _PwmNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PwmNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PwmNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PWM_NET_NAME_UNSPECIFIED: _PwmNetName.ValueType
    PWM_FLOW_RATE_LPS: _PwmNetName.ValueType

class PwmNetName(_PwmNetName, metaclass=_PwmNetNameEnumTypeWrapper):
    ...
PWM_NET_NAME_UNSPECIFIED: PwmNetName.ValueType
PWM_FLOW_RATE_LPS: PwmNetName.ValueType
global___PwmNetName = PwmNetName