"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_NET_NAME_UNSPECIFIED: _GpioNetName.ValueType
    GPIO_DOUT_1: _GpioNetName.ValueType
    GPIO_DOUT_2: _GpioNetName.ValueType
    GPIO_DOUT_3: _GpioNetName.ValueType
    GPIO_DOUT_4: _GpioNetName.ValueType
    GPIO_DEBUG_LED: _GpioNetName.ValueType
    GPIO_BOOT_LED: _GpioNetName.ValueType
    GPIO_INDICATOR_1: _GpioNetName.ValueType
    GPIO_INDICATOR_2: _GpioNetName.ValueType
    GPIO_INDICATOR_3: _GpioNetName.ValueType
    GPIO_INTERLOCK_1: _GpioNetName.ValueType
    GPIO_INTERLOCK_2: _GpioNetName.ValueType
    GPIO_INTERLOCK_3: _GpioNetName.ValueType
    GPIO_INTERLOCK_4: _GpioNetName.ValueType
    GPIO_DAC_N_CLEAR: _GpioNetName.ValueType

class GpioNetName(_GpioNetName, metaclass=_GpioNetNameEnumTypeWrapper):
    ...
GPIO_NET_NAME_UNSPECIFIED: GpioNetName.ValueType
GPIO_DOUT_1: GpioNetName.ValueType
GPIO_DOUT_2: GpioNetName.ValueType
GPIO_DOUT_3: GpioNetName.ValueType
GPIO_DOUT_4: GpioNetName.ValueType
GPIO_DEBUG_LED: GpioNetName.ValueType
GPIO_BOOT_LED: GpioNetName.ValueType
GPIO_INDICATOR_1: GpioNetName.ValueType
GPIO_INDICATOR_2: GpioNetName.ValueType
GPIO_INDICATOR_3: GpioNetName.ValueType
GPIO_INTERLOCK_1: GpioNetName.ValueType
GPIO_INTERLOCK_2: GpioNetName.ValueType
GPIO_INTERLOCK_3: GpioNetName.ValueType
GPIO_INTERLOCK_4: GpioNetName.ValueType
GPIO_DAC_N_CLEAR: GpioNetName.ValueType
global___GpioNetName = GpioNetName

class _SpiNetName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpiNetNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpiNetName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPI_NET_NAME_UNSPECIFIED: _SpiNetName.ValueType
    SPI_ISOSPI_LS: _SpiNetName.ValueType
    SPI_ISOSPI_HS: _SpiNetName.ValueType
    SPI_DAC: _SpiNetName.ValueType

class SpiNetName(_SpiNetName, metaclass=_SpiNetNameEnumTypeWrapper):
    ...
SPI_NET_NAME_UNSPECIFIED: SpiNetName.ValueType
SPI_ISOSPI_LS: SpiNetName.ValueType
SPI_ISOSPI_HS: SpiNetName.ValueType
SPI_DAC: SpiNetName.ValueType
global___SpiNetName = SpiNetName