"""
This file contains all the functionality required to generate C code from our
.dbc file
"""
import logging
import sys
import argparse
from cantools_codegen import *
from canrx_codegen import *
from cantx_codegen import *

if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser()
    valid_boards = ['FSM', 'DCM', 'PDM', 'BMS']
    parser.add_argument('board', help='Choose one of the following: ' + ' '.join(valid_boards))
    parser.add_argument('app_can_tx_source_output', help='Path to output CAN TX .c file for the App layer')
    parser.add_argument('app_can_tx_header_output', help='Path to output CAN TX .h file for the App layer')
    parser.add_argument('io_can_tx_source_output', help='Path to output CAN TX .c file for the IO layer')
    parser.add_argument('io_can_tx_header_output', help='Path to output CAN TX .h file for the IO layer')
    parser.add_argument('app_can_rx_source_output', help='Path to output CAN RX .c file for the App layer')
    parser.add_argument('app_can_rx_header_output', help='Path to output CAN RX .h file for the App layer')
    parser.add_argument('cantools_source_dir',help='Output directory of the source files generated by cantools')
    parser.add_argument('cantools_header_dir',help='Output directory of the header files generated by cantools')
    parser.add_argument('dbc', help='Path to the DBC file')
    args = parser.parse_args()
    if args.board not in valid_boards:
        print('Error: Invalid board name. Valid options: ' + ' '.join(valid_boards))
        sys.exit(1)

    # Configure logging level
    logging.basicConfig(level=logging.DEBUG)

    # DBC name without the file extension
    database_name = os.path.basename(args.dbc).replace('.dbc', '')

    # Load DBC in preparation of cantools
    database = load_file(args.dbc, database_format="dbc")
    for msg in list(msg for msg in map(Message, database.messages)):
        for signal in msg.signals:
            # We don't worry about non-periodic messages because those aren't
            # store in a global table and thus don't have race condition.
            if signal.type_length > 32 and msg.cycle_time != 0:
                raise Exception(
                    "[%s] -> [%s] must be less than 32-bit to ensure atomic access on our 32-bit microcontrollers!"
                    % (msg.snake_name, signal.snake_name))

    print(args.app_can_tx_source_output)
    print(args.app_can_tx_header_output)
    print(args.io_can_tx_source_output)
    print(args.io_can_tx_header_output)
    print(args.app_can_rx_source_output)
    print(args.app_can_rx_header_output)
    print(args.cantools_source_dir)
    print(args.cantools_header_dir)

    # Generate CAN TX code for the App layer
    app_cantx_source = AppCanTxSourceFileGenerator(
        database=database,
        output_path=args.app_can_tx_source_output,
        sender=args.board,
        function_prefix='App_CanTx')
    app_cantx_source.generateSource()
    app_cantx_header = AppCanTxHeaderFileGenerator(
        database=database,
        output_path=args.app_can_tx_header_output,
        sender=args.board,
        function_prefix='App_CanTx')
    app_cantx_header.generateHeader()

    # Generate CAN TX code for the IO layer
    io_cantx_source = IoCanTxSourceFileGenerator(
        database=database,
        output_path=args.io_can_tx_source_output,
        sender=args.board,
        function_prefix='Io_CanTx')
    io_cantx_source.generateSource()
    io_cantx_header = IoCanTxHeaderFileGenerator(
        database=database,
        output_path=args.io_can_tx_header_output,
        sender=args.board,
        function_prefix='Io_CanTx')
    io_cantx_header.generateHeader()

    # Generate CAN RX code for the App layer
    app_canrx_source = CanRxSourceFileGenerator(
        database=database,
        output_path=args.app_can_rx_source_output,
        receiver=args.board,
        function_prefix='App_CanRx')
    app_canrx_source.generateSource()
    app_canrx_header = CanRxHeaderFileGenerator(
        database=database,
        output_path=args.app_can_rx_header_output,
        receiver=args.board,
        function_prefix='App_CanRx')
    app_canrx_header.generateHeader()

    generate_cantools_c_code(
        database=database,
        database_name=database_name,
        source_dir=args.cantools_source_dir,
        header_dir=args.cantools_header_dir)
