#pragma once

#define AGREEMENT_TIME_TO_FAULT (100U)
#define AGREEMENT_TIME_TO_CLEAR (1000U)
#define PAPPS_TIME_TO_FAULT (0U)
#define PAPPS_TIME_TO_CLEAR (10U)
#define SAPPS_TIME_TO_FAULT (0U)
#define SAPPS_TIME_TO_CLEAR (10U)