#pragma once

#define PRIMARY_FLOW_METER_MIN_FLOW_RATE 1.0f
#define PRIMARY_FLOW_METER_MAX_FLOW_RATE 30.0f
#define SECONDARY_FLOW_METER_MIN_FLOW_RATE 1.0f
#define SECONDARY_FLOW_METER_MAX_FLOW_RATE 30.0f
