#pragma once

#define PAPPS_ENTRY_HIGH_MS (10U)
#define PAPPS_EXIT_HIGH_MS (10U)
#define SAPPS_ENTRY_HIGH_MS (10U)
#define SAPPS_EXIT_HIGH_MS (10U)
#define APPS_ENTRY_HIGH_MS (100U)
#define APPS_EXIT_HIGH_MS (1000U)
#define APPS_AND_BRAKE_ENTRY_HIGH_MS (1U)
#define APPS_AND_BRAKE_EXIT_HIGH_MS (1U)
#define FLOW_METER_ENTRY_HIGH_MS (1000U)
#define FLOW_METER_EXIT_HIGH_MS (1000U)
