#pragma once

#define PAPPS_ENTRY_HIGH_MS 10
#define PAPPS_EXIT_HIGH_MS 10
#define SAPPS_ENTRY_HIGH_MS 10
#define SAPPS_EXIT_HIGH_MS 10
#define APPS_ENTRY_HIGH_MS 100
#define APPS_EXIT_HIGH_MS 1000
#define APPS_AND_BRAKE_ENTRY_HIGH_MS 1
#define APPS_AND_BRAKE_EXIT_HIGH_MS 1
