#pragma once

#define AGREEMENT_TIME_TO_FAULT (100U)
#define AGREEMENT_TIME_TO_CLEAR (1000U)
#define PAPPS_OCSC_TIME_TO_FAULT (10U)
#define PAPPS_OCSC_TIME_TO_CLEAR (10U)
#define SAPPS_OCSC_TIME_TO_FAULT (10U)
#define SAPPS_OCSC_TIME_TO_CLEAR (10U)
// TODO relook at these values
#define APP_BRAKE_TIME_TO_FAULT (10U)
#define APP_BRAKE_TIME_TO_CLEAR (10U)
