/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.6.1 
 */

#include <string.h>

#include "Inc/CanMsgs.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int CanMsgs_symbol1_pack(
    uint8_t *dst_p,
    const struct CanMsgs_symbol1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[5] |= pack_left_shift_u8(src_p->some_enum, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->enum_signal, 1u, 0xfeu);
    dst_p[6] |= pack_right_shift_u8(src_p->enum_signal, 7u, 0x01u);

    return (8);
}

int CanMsgs_symbol1_unpack(
    struct CanMsgs_symbol1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->some_enum |= unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->enum_signal |= unpack_right_shift_u8(src_p[5], 1u, 0xfeu);
    dst_p->enum_signal |= unpack_left_shift_u8(src_p[6], 7u, 0x01u);

    return (0);
}

uint8_t CanMsgs_symbol1_some_enum_encode(double value)
{
    return (uint8_t)(value);
}

double CanMsgs_symbol1_some_enum_decode(uint8_t value)
{
    return ((double)value);
}

bool CanMsgs_symbol1_some_enum_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t CanMsgs_symbol1_enum_signal_encode(double value)
{
    return (uint8_t)(value);
}

double CanMsgs_symbol1_enum_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool CanMsgs_symbol1_enum_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
