#pragma once

#define DIE_TEMP_DEGC_TO_REENABLE_CELL_BALANCING 110.0f
#define DIE_TEMP_DEGC_TO_REENABLE_CHARGER 115.0f
#define DIE_TEMP_DEGC_TO_DISABLE_CELL_BALANCING 115.0f
#define DIE_TEMP_DEGC_TO_DISABLE_CHARGER 120.0f

#define MIN_INTERNAL_DIE_TEMP_DEGC 0.0f
#define MAX_INTERNAL_DIE_TEMP_DEGC 120.0f
