#pragma once

#define REENABLE_CELL_BALANCING_DIE_TEMP_DEGC 110.0f
#define REENABLE_CHARGER_DIE_TEMP_DEGC 115.0f
#define DISABLE_CELL_BALANCING_DIE_TEMP_DEGC 115.0f
#define DISABLE_CHARGER_DIE_TEMP_DEGC 120.0f
#define MIN_INTERNAL_DIE_TEMP_DEGC 0.0f
#define MAX_INTERNAL_DIE_TEMP_DEGC DISABLE_CHARGER_DIE_TEMP_DEGC
