#pragma once

#define DIE_TEMP_TO_REENABLE_CELL_BALANCING_DEGC 110.0f
#define DIE_TEMP_TO_REENABLE_CHARGER_DEGC 115.0f
#define DIE_TEMP_TO_DISABLE_CELL_BALANCING_DEGC 115.0f
#define DIE_TEMP_TO_DISABLE_CHARGER_DEGC 120.0f

#define MIN_ITMP_DEGC 0.0f
#define MAX_ITMP_DEGC 120.0f
