# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telem.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="telem.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0btelem.proto"@\n\x0cTelemMessage\x12\x0e\n\x06\x63\x61n_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\x12\x12\n\ntime_stamp\x18\x03 \x01(\x05\x62\x06proto3',
)


_TELEMMESSAGE = _descriptor.Descriptor(
    name="TelemMessage",
    full_name="TelemMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="can_id",
            full_name="TelemMessage.can_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="TelemMessage.data",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="time_stamp",
            full_name="TelemMessage.time_stamp",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=15,
    serialized_end=79,
)

DESCRIPTOR.message_types_by_name["TelemMessage"] = _TELEMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelemMessage = _reflection.GeneratedProtocolMessageType(
    "TelemMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _TELEMMESSAGE,
        "__module__": "telem_pb2",
        # @@protoc_insertion_point(class_scope:TelemMessage)
    },
)
_sym_db.RegisterMessage(TelemMessage)


# @@protoc_insertion_point(module_scope)
