name: tracksight-backend-frontend
services:
  backend:
    extends:
      file: ../common.yml
      service: backend
  frontend:
    extends:
      file: ../common.yml
      service: frontend
    command:
      [
        "npm",
        "start"
     ]