name: tracksight-backend
services:
  influx:
    extends:
      file: ../common.yml
      service: influx
  backend:
    extends:
      file: ../common.yml
      service: backend

volumes:
  influxdb:
