name: tracksight-docker
services:
  influx:
    extends:
      file: common.yml
      service: influx
  backend:
    extends:
      file: common.yml
      service: backend
    command:
      [
        "python3",
        "app/app.py"
      ]
  frontend:
    extends:
      file: common.yml
      service: frontend
    command:
      [
        "npm",
        "start"
     ]
