name: tracksight-log
services:
  influx:
    extends:
      file: common.yml
      service: influx
  backend:
    extends:
      file: common.yml
      service: backend
    # Start telemetry in log file mode.
    command:
      [
        "python3",
        "app/telemetry.py",
        "--mode",
        "log",
        "--data-file",
        "${DATA_FILE}",
        "--debug"
      ]
    volumes:
      - ../backend/logs:/backend/logs
      - ../backend/data:/backend/data
  frontend:
    extends:
      file: common.yml
      service: frontend
