name: tracksight-mock
services:
  influx:
    extends:
      file: common.yml
      service: influx
  live_data:
    extends:
      file: common.yml
      service: live_data
    command:
      [
        "python3",
        "app/app.py",
        "--mode",
        "mock",
        "-f",
        "app/mock_data/sample_data1.csv",
        "--debug",
      ]
  # frontend:
  #   extends:
  #     file: common.yml
  #     service: frontend
