name: tracksight-wireless
services:
  influx:
    extends:
      file: common.yml
      service: influx
  # backend:
  #   extends:
  #     file: common.yml
  #     service: backend
  #   # Start telemetry in log file mode.
  #   command:
  #     [
  #       "python3",
  #       "app/telemetry.py",
  #     ]
  live_data:
    extends:
      file: common.yml
      service: live_data
    command:
      [
        "python3",
        "app/app.py",
        "--mode",
        "wireless",
        "--serial-port",
        "TODO"
      ]
  frontend:
    extends:
      file: common.yml
      service: frontend
