# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FSM.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FSM.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tFSM.proto*E\n\x0e\x46smGpioNetName\x12!\n\x1d\x46SM_GPIO_NET_NAME_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x46SM_LED_GPIO\x10\x01*J\n\rFsmAdcNetName\x12 \n\x1c\x46SM_ADC_NET_NAME_UNSPECIFIED\x10\x00\x12\x17\n\x13\x46SM_INV_R_PWR_I_SNS\x10\x01\x62\x06proto3'
)

_FSMGPIONETNAME = _descriptor.EnumDescriptor(
  name='FsmGpioNetName',
  full_name='FsmGpioNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FSM_GPIO_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FSM_LED_GPIO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=13,
  serialized_end=82,
)
_sym_db.RegisterEnumDescriptor(_FSMGPIONETNAME)

FsmGpioNetName = enum_type_wrapper.EnumTypeWrapper(_FSMGPIONETNAME)
_FSMADCNETNAME = _descriptor.EnumDescriptor(
  name='FsmAdcNetName',
  full_name='FsmAdcNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FSM_ADC_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FSM_INV_R_PWR_I_SNS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_FSMADCNETNAME)

FsmAdcNetName = enum_type_wrapper.EnumTypeWrapper(_FSMADCNETNAME)
FSM_GPIO_NET_NAME_UNSPECIFIED = 0
FSM_LED_GPIO = 1
FSM_ADC_NET_NAME_UNSPECIFIED = 0
FSM_INV_R_PWR_I_SNS = 1


DESCRIPTOR.enum_types_by_name['FsmGpioNetName'] = _FSMGPIONETNAME
DESCRIPTOR.enum_types_by_name['FsmAdcNetName'] = _FSMADCNETNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
