# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RSM.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RSM.proto',
  package='RSM',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tRSM.proto\x12\x03RSM\"M\n\x08GpioRead\x12\"\n\x08net_name\x18\x01 \x01(\x0e\x32\x10.RSM.GpioNetName\x12\x1d\n\x05value\x18\x02 \x01(\x0e\x32\x0e.RSM.GpioValue\"N\n\tGpioWrite\x12\"\n\x08net_name\x18\x01 \x01(\x0e\x32\x10.RSM.GpioNetName\x12\x1d\n\x05value\x18\x02 \x01(\x0e\x32\x0e.RSM.GpioValue\"7\n\x03\x41\x64\x63\x12!\n\x08net_name\x18\x01 \x01(\x0e\x32\x0f.RSM.AdcNetName\x12\r\n\x05value\x18\x02 \x01(\x02\"|\n\x0c\x44\x65\x62ugMessage\x12\"\n\tgpio_read\x18\x01 \x01(\x0b\x32\r.RSM.GpioReadH\x00\x12$\n\ngpio_write\x18\x02 \x01(\x0b\x32\x0e.RSM.GpioWriteH\x00\x12\x17\n\x03\x61\x64\x63\x18\x03 \x01(\x0b\x32\x08.RSM.AdcH\x00\x42\t\n\x07payload*\x9a\x01\n\x0bGpioNetName\x12\x1d\n\x19GPIO_NET_NAME_UNSPECIFIED\x10\x00\x12\x0c\n\x08NCHIMERA\x10\x01\x12\x07\n\x03LED\x10\x02\x12\x0e\n\nRAD_FAN_EN\x10\x03\x12\x0b\n\x07\x46R_STBY\x10\x04\x12\x16\n\x12\x42RAKE_LIGHT_EN_3V3\x10\x05\x12\x0e\n\nACC_FAN_EN\x10\x06\x12\x10\n\x0cNProgram_3V3\x10\x07*:\n\tGpioValue\x12\x1a\n\x16GPIO_VALUE_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02*\xfa\x01\n\nAdcNetName\x12\x1c\n\x18\x41\x44\x43_NET_NAME_UNSPECIFIED\x10\x00\x12\x11\n\rACC_FAN_I_SNS\x10\x01\x12\x11\n\rRAD_FAN_I_SNS\x10\x02\x12\x18\n\x14\x43oolantPressure1_3V3\x10\x03\x12\x18\n\x14\x43oolantPressure2_3V3\x10\x04\x12\x0b\n\x07LC3_OUT\x10\x05\x12\x16\n\x12SUSP_TRAVEL_RR_3V3\x10\x06\x12\x16\n\x12SUSP_TRAVEL_RL_3V3\x10\x07\x12\x14\n\x10\x43oolantTemp2_3V3\x10\x08\x12\x14\n\x10\x43oolantTemp1_3V3\x10\t\x12\x0b\n\x07LC4_OUT\x10\nb\x06proto3'
)

_GPIONETNAME = _descriptor.EnumDescriptor(
  name='GpioNetName',
  full_name='RSM.GpioNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GPIO_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NCHIMERA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAD_FAN_EN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FR_STBY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BRAKE_LIGHT_EN_3V3', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACC_FAN_EN', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NProgram_3V3', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=361,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_GPIONETNAME)

GpioNetName = enum_type_wrapper.EnumTypeWrapper(_GPIONETNAME)
_GPIOVALUE = _descriptor.EnumDescriptor(
  name='GpioValue',
  full_name='RSM.GpioValue',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GPIO_VALUE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=575,
)
_sym_db.RegisterEnumDescriptor(_GPIOVALUE)

GpioValue = enum_type_wrapper.EnumTypeWrapper(_GPIOVALUE)
_ADCNETNAME = _descriptor.EnumDescriptor(
  name='AdcNetName',
  full_name='RSM.AdcNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADC_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACC_FAN_I_SNS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAD_FAN_I_SNS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CoolantPressure1_3V3', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CoolantPressure2_3V3', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LC3_OUT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUSP_TRAVEL_RR_3V3', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUSP_TRAVEL_RL_3V3', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CoolantTemp2_3V3', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CoolantTemp1_3V3', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LC4_OUT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=578,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_ADCNETNAME)

AdcNetName = enum_type_wrapper.EnumTypeWrapper(_ADCNETNAME)
GPIO_NET_NAME_UNSPECIFIED = 0
NCHIMERA = 1
LED = 2
RAD_FAN_EN = 3
FR_STBY = 4
BRAKE_LIGHT_EN_3V3 = 5
ACC_FAN_EN = 6
NProgram_3V3 = 7
GPIO_VALUE_UNSPECIFIED = 0
LOW = 1
HIGH = 2
ADC_NET_NAME_UNSPECIFIED = 0
ACC_FAN_I_SNS = 1
RAD_FAN_I_SNS = 2
CoolantPressure1_3V3 = 3
CoolantPressure2_3V3 = 4
LC3_OUT = 5
SUSP_TRAVEL_RR_3V3 = 6
SUSP_TRAVEL_RL_3V3 = 7
CoolantTemp2_3V3 = 8
CoolantTemp1_3V3 = 9
LC4_OUT = 10



_GPIOREAD = _descriptor.Descriptor(
  name='GpioRead',
  full_name='RSM.GpioRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_name', full_name='RSM.GpioRead.net_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RSM.GpioRead.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=95,
)


_GPIOWRITE = _descriptor.Descriptor(
  name='GpioWrite',
  full_name='RSM.GpioWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_name', full_name='RSM.GpioWrite.net_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RSM.GpioWrite.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=175,
)


_ADC = _descriptor.Descriptor(
  name='Adc',
  full_name='RSM.Adc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_name', full_name='RSM.Adc.net_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RSM.Adc.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=232,
)


_DEBUGMESSAGE = _descriptor.Descriptor(
  name='DebugMessage',
  full_name='RSM.DebugMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpio_read', full_name='RSM.DebugMessage.gpio_read', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpio_write', full_name='RSM.DebugMessage.gpio_write', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adc', full_name='RSM.DebugMessage.adc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='RSM.DebugMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=234,
  serialized_end=358,
)

_GPIOREAD.fields_by_name['net_name'].enum_type = _GPIONETNAME
_GPIOREAD.fields_by_name['value'].enum_type = _GPIOVALUE
_GPIOWRITE.fields_by_name['net_name'].enum_type = _GPIONETNAME
_GPIOWRITE.fields_by_name['value'].enum_type = _GPIOVALUE
_ADC.fields_by_name['net_name'].enum_type = _ADCNETNAME
_DEBUGMESSAGE.fields_by_name['gpio_read'].message_type = _GPIOREAD
_DEBUGMESSAGE.fields_by_name['gpio_write'].message_type = _GPIOWRITE
_DEBUGMESSAGE.fields_by_name['adc'].message_type = _ADC
_DEBUGMESSAGE.oneofs_by_name['payload'].fields.append(
  _DEBUGMESSAGE.fields_by_name['gpio_read'])
_DEBUGMESSAGE.fields_by_name['gpio_read'].containing_oneof = _DEBUGMESSAGE.oneofs_by_name['payload']
_DEBUGMESSAGE.oneofs_by_name['payload'].fields.append(
  _DEBUGMESSAGE.fields_by_name['gpio_write'])
_DEBUGMESSAGE.fields_by_name['gpio_write'].containing_oneof = _DEBUGMESSAGE.oneofs_by_name['payload']
_DEBUGMESSAGE.oneofs_by_name['payload'].fields.append(
  _DEBUGMESSAGE.fields_by_name['adc'])
_DEBUGMESSAGE.fields_by_name['adc'].containing_oneof = _DEBUGMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['GpioRead'] = _GPIOREAD
DESCRIPTOR.message_types_by_name['GpioWrite'] = _GPIOWRITE
DESCRIPTOR.message_types_by_name['Adc'] = _ADC
DESCRIPTOR.message_types_by_name['DebugMessage'] = _DEBUGMESSAGE
DESCRIPTOR.enum_types_by_name['GpioNetName'] = _GPIONETNAME
DESCRIPTOR.enum_types_by_name['GpioValue'] = _GPIOVALUE
DESCRIPTOR.enum_types_by_name['AdcNetName'] = _ADCNETNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpioRead = _reflection.GeneratedProtocolMessageType('GpioRead', (_message.Message,), {
  'DESCRIPTOR' : _GPIOREAD,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:RSM.GpioRead)
  })
_sym_db.RegisterMessage(GpioRead)

GpioWrite = _reflection.GeneratedProtocolMessageType('GpioWrite', (_message.Message,), {
  'DESCRIPTOR' : _GPIOWRITE,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:RSM.GpioWrite)
  })
_sym_db.RegisterMessage(GpioWrite)

Adc = _reflection.GeneratedProtocolMessageType('Adc', (_message.Message,), {
  'DESCRIPTOR' : _ADC,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:RSM.Adc)
  })
_sym_db.RegisterMessage(Adc)

DebugMessage = _reflection.GeneratedProtocolMessageType('DebugMessage', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGMESSAGE,
  '__module__' : 'RSM_pb2'
  # @@protoc_insertion_point(class_scope:RSM.DebugMessage)
  })
_sym_db.RegisterMessage(DebugMessage)


# @@protoc_insertion_point(module_scope)
