# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RSM.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RSM.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tRSM.proto*E\n\x0eRsmGpioNetName\x12!\n\x1dRSM_GPIO_NET_NAME_UNSPECIFIED\x10\x00\x12\x10\n\x0cRSM_LED_GPIO\x10\x01*J\n\rRsmAdcNetName\x12 \n\x1cRSM_ADC_NET_NAME_UNSPECIFIED\x10\x00\x12\x17\n\x13RSM_INV_R_PWR_I_SNS\x10\x01\x62\x06proto3'
)

_RSMGPIONETNAME = _descriptor.EnumDescriptor(
  name='RsmGpioNetName',
  full_name='RsmGpioNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RSM_GPIO_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RSM_LED_GPIO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=13,
  serialized_end=82,
)
_sym_db.RegisterEnumDescriptor(_RSMGPIONETNAME)

RsmGpioNetName = enum_type_wrapper.EnumTypeWrapper(_RSMGPIONETNAME)
_RSMADCNETNAME = _descriptor.EnumDescriptor(
  name='RsmAdcNetName',
  full_name='RsmAdcNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RSM_ADC_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RSM_INV_R_PWR_I_SNS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_RSMADCNETNAME)

RsmAdcNetName = enum_type_wrapper.EnumTypeWrapper(_RSMADCNETNAME)
RSM_GPIO_NET_NAME_UNSPECIFIED = 0
RSM_LED_GPIO = 1
RSM_ADC_NET_NAME_UNSPECIFIED = 0
RSM_INV_R_PWR_I_SNS = 1


DESCRIPTOR.enum_types_by_name['RsmGpioNetName'] = _RSMGPIONETNAME
DESCRIPTOR.enum_types_by_name['RsmAdcNetName'] = _RSMADCNETNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
