# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VC.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VC.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08VC.proto*B\n\rVcGpioNetName\x12 \n\x1cVC_GPIO_NET_NAME_UNSPECIFIED\x10\x00\x12\x0f\n\x0bVC_LED_GPIO\x10\x01*G\n\x0cVcAdcNetName\x12\x1f\n\x1bVC_ADC_NET_NAME_UNSPECIFIED\x10\x00\x12\x16\n\x12VC_INV_R_PWR_I_SNS\x10\x01\x62\x06proto3'
)

_VCGPIONETNAME = _descriptor.EnumDescriptor(
  name='VcGpioNetName',
  full_name='VcGpioNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VC_GPIO_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VC_LED_GPIO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=12,
  serialized_end=78,
)
_sym_db.RegisterEnumDescriptor(_VCGPIONETNAME)

VcGpioNetName = enum_type_wrapper.EnumTypeWrapper(_VCGPIONETNAME)
_VCADCNETNAME = _descriptor.EnumDescriptor(
  name='VcAdcNetName',
  full_name='VcAdcNetName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VC_ADC_NET_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VC_INV_R_PWR_I_SNS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=80,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_VCADCNETNAME)

VcAdcNetName = enum_type_wrapper.EnumTypeWrapper(_VCADCNETNAME)
VC_GPIO_NET_NAME_UNSPECIFIED = 0
VC_LED_GPIO = 1
VC_ADC_NET_NAME_UNSPECIFIED = 0
VC_INV_R_PWR_I_SNS = 1


DESCRIPTOR.enum_types_by_name['VcGpioNetName'] = _VCGPIONETNAME
DESCRIPTOR.enum_types_by_name['VcAdcNetName'] = _VCADCNETNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
