name: Push Release
description: Push a release to the repo under a given tag
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Delete ONE other releases on tag
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release delete ${{github.head_ref}}_tag --repo UBCFormulaElectric/Consolidated-Firmware --cleanup-tag --yes
      continue-on-error: true
    - name: Create Tag
      shell: bash
      run: |
        git tag ${{github.head_ref}}_tag -f
        git push origin ${{github.head_ref}}_tag -f
    - name: Create Release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{github.head_ref}}_tag \
          CanMsgs.dbc/CanMsgs.dbc \
          --title "${{github.head_ref}} DBC File" \
          --notes "DBC Files generated for ${{github.head_ref}}" \
          --repo UBCFormulaElectric/Consolidated-Firmware \
          --target "${{github.SHA}}"