name: Push Release
description: Push a release to the repo under a given tag
inputs:
  files: # id of input
    description: The files to upload (must exist in the current working directory)
    required: true
    default: 'World'
  latest:
    description: Whether to push to the latest tag
    required: false
    default: false
  title:
    description: The title of the release
    required: true
  body:
    description: The body of the release
    required: true

runs:
  using: "composite"
  env:
    TAG_NAME: ${{ github.ref == 'refs/heads/master' && 'latest' || github.head_ref + '_tag' }}
  steps:
    - name: Delete ONE other releases on tag
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release delete ${{ env.TAG_NAME }} --repo UBCFormulaElectric/Consolidated-Firmware --cleanup-tag --yes
      continue-on-error: true
    - name: Create Tag
      shell: bash
      run: |
        git tag ${{ env.TAG_NAME }} -f
        git push origin ${{ env.TAG_NAME }}g -f

    - name: Make file name one line
      shell: bash
      run: |
        MY_STRING=$(cat << EOF
        ${{inputs.files}}
        EOF
        )
        MY_STRING="${MY_STRING//$'\n'/' '}"
        echo "::set-output name=content::$MY_STRING"
      id: my_string

    - name: Create Release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ env.TAG_NAME }} ${{ steps.my_string.outputs.content }} \
          --title ${{inputs.title}} \
          --notes ${{inputs.body}} \
          --repo UBCFormulaElectric/Consolidated-Firmware