name: Push Release
description: Push a release to the repo under a given tag
inputs:
  files: # id of input
    description: The files to upload (must exist in the current working directory)
    required: true
    default: 'World'
  tag_name:
    description: The tag to push the release to
    required: true
  title:
    description: The title of the release
    required: true
  body:
    description: The body of the release
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete ONE other releases on tag
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release delete ${{ inputs.tag_name }} --repo UBCFormulaElectric/Consolidated-Firmware --cleanup-tag --yes
      continue-on-error: true
    - name: Create Tag
      shell: bash
      run: |
        git tag ${{ inputs.tag_name }} -f
        git push origin ${{ inputs.tag_name }} -f

    - name: Make file name one line
      shell: bash
      run: |
        MY_STRING=$(cat << EOF
        ${{inputs.files}}
        EOF
        )
        MY_STRING="${MY_STRING//$'\n'/' '}"
        echo "name=$MY_STRING" >> >> $GITHUB_OUTPUT
      id: my_string

    - name: Create Release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ inputs.tag_name }} ${{ steps.my_string.outputs.content }} \
          --title ${{inputs.title}} \
          --notes ${{inputs.body}} \
          --repo UBCFormulaElectric/Consolidated-Firmware