/**
 * @note This file is auto-generated. Do not modify!
 */
// clang-format off

#pragma once

/* ------------------------------- Includes ------------------------------- */

#include <stdint.h>
#include <stdbool.h>

/* -------------------------------- Macros -------------------------------- */

// Msg IDs
#define CAN_MSG_GSM_GSM_VITALS_ID (603)
#define CAN_MSG_GSM_GSM_WARNINGS_ID (604)
#define CAN_MSG_GSM_STACK_REMAINING_ID (606)
#define CAN_MSG_GSM_COMMIT_INFO_ID (605)
#define CAN_MSG_DIM_WARNINGS_ID (500)
#define CAN_MSG_DIM_FAULTS_ID (501)
#define CAN_MSG_DCM_WARNINGS_ID (200)
#define CAN_MSG_DCM_FAULTS_ID (201)
#define CAN_MSG_BMS_WARNINGS_ID (150)
#define CAN_MSG_BMS_FAULTS_ID (151)
#define CAN_MSG_PDM_WARNINGS_ID (400)
#define CAN_MSG_PDM_FAULTS_ID (401)
#define CAN_MSG_DEBUG_CAN_MODE_ID (701)
#define CAN_MSG_FSM_WARNINGS_ID (350)
#define CAN_MSG_FSM_FAULTS_ID (351)

// Msg lengths (in bytes)
#define CAN_MSG_GSM_GSM_VITALS_BYTES (1)
#define CAN_MSG_GSM_GSM_WARNINGS_BYTES (4)
#define CAN_MSG_GSM_STACK_REMAINING_BYTES (5)
#define CAN_MSG_GSM_COMMIT_INFO_BYTES (5)

// Periodic msg cycle times (in MS)
#define CAN_MSG_GSM_GSM_VITALS_CYCLE_TIME_MS (100)
#define CAN_MSG_GSM_GSM_WARNINGS_CYCLE_TIME_MS (1000)
#define CAN_MSG_GSM_STACK_REMAINING_CYCLE_TIME_MS (100)
#define CAN_MSG_GSM_COMMIT_INFO_CYCLE_TIME_MS (100)

// Signal starting values
#define CANSIG_GSM_GSM_VITALS_GSM_HEARTBEAT_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1_HZ_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK100_HZ_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1K_HZ_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_TX_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_RX_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_TX_OVERFLOW_COUNT_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_RX_OVERFLOW_COUNT_START_VAL (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_TASK_NAME_START_VAL (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1_HZ_START_VAL (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK100_HZ_START_VAL (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1K_HZ_START_VAL (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_RX_START_VAL (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_TX_START_VAL (0) // %
#define CANSIG_GSM_COMMIT_INFO_GSM_HASH_START_VAL (0)
#define CANSIG_GSM_COMMIT_INFO_GSM_CLEAN_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_WATCHDOG_TIMEOUT_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_TX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_DIM_WARNINGS_DIM_RX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_DIM_FAULTS_DIM_MISSING_HEARTBEAT_FAULT_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_WATCHDOG_TIMEOUT_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_TX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_DCM_WARNINGS_DCM_RX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_DCM_FAULTS_DCM_MISSING_HEARTBEAT_FAULT_START_VAL (0)
#define CANSIG_DCM_FAULTS_DCM_LEFT_INVERTER_FAULT_START_VAL (0)
#define CANSIG_DCM_FAULTS_DCM_RIGHT_INVERTER_FAULT_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_WATCHDOG_TIMEOUT_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_TX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_BMS_WARNINGS_BMS_RX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_MISSING_HEARTBEAT_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_STATE_MACHINE_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERVOLTAGE_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERVOLTAGE_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_MODULE_COMMUNICATION_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERTEMP_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERTEMP_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_DISCONNECTED_DURING_CHARGE_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_EXTERNAL_SHUTDOWN_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_TRACTIVE_SYSTEM_OVERCURRENT_FAULT_START_VAL (0)
#define CANSIG_BMS_FAULTS_BMS_PRECHARGE_FAILURE_FAULT_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_WATCHDOG_TIMEOUT_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_TX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_PDM_WARNINGS_PDM_RX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_PDM_FAULTS_PDM_DUMMY_FAULT_START_VAL (0)
#define CANSIG_DEBUG_CAN_MODE_DEBUG_ENABLE_DEBUG_MODE_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_WATCHDOG_TIMEOUT_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_TX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_RX_OVERFLOW_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_LEFT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_RIGHT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OCSC_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_FRONT_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_REAR_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_FLOW_RATE_OUT_OF_RANGE_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_BRAKE_APPS_DISAGREEMENT_WARNING_START_VAL (0)
#define CANSIG_FSM_WARNINGS_FSM_APPS_DISAGREEMENT_WARNING_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_MISSING_HEARTBEAT_FAULT_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_STATE_MACHINE_FAULT_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_PAPPS_OCSC_FAULT_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_SAPPS_OCSC_FAULT_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_FLOW_METER_UNDERFLOW_FAULT_START_VAL (0)
#define CANSIG_FSM_FAULTS_FSM_TORQUE_PLAUSABILITY_FAILED_FAULT_START_VAL (0)

// Scale/offset values for encoding/decoding signals
#define CANSIG_GSM_GSM_VITALS_GSM_HEARTBEAT_SCALE (1)
#define CANSIG_GSM_GSM_VITALS_GSM_HEARTBEAT_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1_HZ_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1_HZ_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK100_HZ_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK100_HZ_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1K_HZ_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1K_HZ_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_TX_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_TX_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_RX_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_RX_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_TX_OVERFLOW_COUNT_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_TX_OVERFLOW_COUNT_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_RX_OVERFLOW_COUNT_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_RX_OVERFLOW_COUNT_OFFSET (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_TASK_NAME_SCALE (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_TASK_NAME_OFFSET (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1_HZ_SCALE (1)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1_HZ_OFFSET (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK100_HZ_SCALE (1)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK100_HZ_OFFSET (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1K_HZ_SCALE (1)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1K_HZ_OFFSET (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_RX_SCALE (1)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_RX_OFFSET (0)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_TX_SCALE (1)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_TX_OFFSET (0)
#define CANSIG_GSM_COMMIT_INFO_GSM_HASH_SCALE (1)
#define CANSIG_GSM_COMMIT_INFO_GSM_HASH_OFFSET (0)
#define CANSIG_GSM_COMMIT_INFO_GSM_CLEAN_SCALE (1)
#define CANSIG_GSM_COMMIT_INFO_GSM_CLEAN_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_WATCHDOG_TIMEOUT_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_WATCHDOG_TIMEOUT_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_TX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_TX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_DIM_WARNINGS_DIM_RX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_DIM_WARNINGS_DIM_RX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_DIM_FAULTS_DIM_MISSING_HEARTBEAT_FAULT_SCALE (1)
#define CANSIG_DIM_FAULTS_DIM_MISSING_HEARTBEAT_FAULT_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_WATCHDOG_TIMEOUT_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_WATCHDOG_TIMEOUT_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_TX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_TX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_DCM_WARNINGS_DCM_RX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_DCM_WARNINGS_DCM_RX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_DCM_FAULTS_DCM_MISSING_HEARTBEAT_FAULT_SCALE (1)
#define CANSIG_DCM_FAULTS_DCM_MISSING_HEARTBEAT_FAULT_OFFSET (0)
#define CANSIG_DCM_FAULTS_DCM_LEFT_INVERTER_FAULT_SCALE (1)
#define CANSIG_DCM_FAULTS_DCM_LEFT_INVERTER_FAULT_OFFSET (0)
#define CANSIG_DCM_FAULTS_DCM_RIGHT_INVERTER_FAULT_SCALE (1)
#define CANSIG_DCM_FAULTS_DCM_RIGHT_INVERTER_FAULT_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_WATCHDOG_TIMEOUT_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_WATCHDOG_TIMEOUT_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_TX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_TX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_BMS_WARNINGS_BMS_RX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_BMS_WARNINGS_BMS_RX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_MISSING_HEARTBEAT_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_MISSING_HEARTBEAT_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_STATE_MACHINE_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_STATE_MACHINE_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERVOLTAGE_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERVOLTAGE_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERVOLTAGE_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERVOLTAGE_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_MODULE_COMMUNICATION_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_MODULE_COMMUNICATION_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERTEMP_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERTEMP_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERTEMP_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERTEMP_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_DISCONNECTED_DURING_CHARGE_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_DISCONNECTED_DURING_CHARGE_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_EXTERNAL_SHUTDOWN_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_EXTERNAL_SHUTDOWN_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_TRACTIVE_SYSTEM_OVERCURRENT_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_TRACTIVE_SYSTEM_OVERCURRENT_FAULT_OFFSET (0)
#define CANSIG_BMS_FAULTS_BMS_PRECHARGE_FAILURE_FAULT_SCALE (1)
#define CANSIG_BMS_FAULTS_BMS_PRECHARGE_FAILURE_FAULT_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_WATCHDOG_TIMEOUT_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_WATCHDOG_TIMEOUT_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_TX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_TX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_PDM_WARNINGS_PDM_RX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_PDM_WARNINGS_PDM_RX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_PDM_FAULTS_PDM_DUMMY_FAULT_SCALE (1)
#define CANSIG_PDM_FAULTS_PDM_DUMMY_FAULT_OFFSET (0)
#define CANSIG_DEBUG_CAN_MODE_DEBUG_ENABLE_DEBUG_MODE_SCALE (1)
#define CANSIG_DEBUG_CAN_MODE_DEBUG_ENABLE_DEBUG_MODE_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_WATCHDOG_TIMEOUT_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_WATCHDOG_TIMEOUT_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_TX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_TX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_RX_OVERFLOW_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_RX_OVERFLOW_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_LEFT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_LEFT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_RIGHT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_RIGHT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OCSC_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OCSC_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_FRONT_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_FRONT_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_REAR_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_REAR_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_FLOW_RATE_OUT_OF_RANGE_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_FLOW_RATE_OUT_OF_RANGE_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_BRAKE_APPS_DISAGREEMENT_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_BRAKE_APPS_DISAGREEMENT_WARNING_OFFSET (0)
#define CANSIG_FSM_WARNINGS_FSM_APPS_DISAGREEMENT_WARNING_SCALE (1)
#define CANSIG_FSM_WARNINGS_FSM_APPS_DISAGREEMENT_WARNING_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_MISSING_HEARTBEAT_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_MISSING_HEARTBEAT_FAULT_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_STATE_MACHINE_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_STATE_MACHINE_FAULT_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_PAPPS_OCSC_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_PAPPS_OCSC_FAULT_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_SAPPS_OCSC_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_SAPPS_OCSC_FAULT_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_FLOW_METER_UNDERFLOW_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_FLOW_METER_UNDERFLOW_FAULT_OFFSET (0)
#define CANSIG_FSM_FAULTS_FSM_TORQUE_PLAUSABILITY_FAILED_FAULT_SCALE (1)
#define CANSIG_FSM_FAULTS_FSM_TORQUE_PLAUSABILITY_FAILED_FAULT_OFFSET (0)

// Min/max allowed values for signals
#define CANSIG_GSM_GSM_VITALS_GSM_HEARTBEAT_MIN (0)
#define CANSIG_GSM_GSM_VITALS_GSM_HEARTBEAT_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1_HZ_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1_HZ_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK100_HZ_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK100_HZ_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1K_HZ_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK1K_HZ_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_TX_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_TX_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_RX_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_STACK_WATERMARK_ABOVE_THRESHOLD_TASK_CAN_RX_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_MAX (1)
#define CANSIG_GSM_GSM_WARNINGS_GSM_TX_OVERFLOW_COUNT_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_TX_OVERFLOW_COUNT_MAX (255)
#define CANSIG_GSM_GSM_WARNINGS_GSM_RX_OVERFLOW_COUNT_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_RX_OVERFLOW_COUNT_MAX (255)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_TASK_NAME_MIN (0)
#define CANSIG_GSM_GSM_WARNINGS_GSM_WATCHDOG_TIMEOUT_TASK_NAME_MAX (4)
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1_HZ_MIN (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1_HZ_MAX (100) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK100_HZ_MIN (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK100_HZ_MAX (100) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1K_HZ_MIN (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK1K_HZ_MAX (100) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_RX_MIN (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_RX_MAX (100) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_TX_MIN (0) // %
#define CANSIG_GSM_STACK_REMAINING_GSM_STACK_REMAINING_TASK_CAN_TX_MAX (100) // %
#define CANSIG_GSM_COMMIT_INFO_GSM_HASH_MIN (0)
#define CANSIG_GSM_COMMIT_INFO_GSM_HASH_MAX (4294967295)
#define CANSIG_GSM_COMMIT_INFO_GSM_CLEAN_MIN (0)
#define CANSIG_GSM_COMMIT_INFO_GSM_CLEAN_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_WATCHDOG_TIMEOUT_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_WATCHDOG_TIMEOUT_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_TX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_TX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_DIM_WARNINGS_DIM_RX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_DIM_WARNINGS_DIM_RX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_DIM_FAULTS_DIM_MISSING_HEARTBEAT_FAULT_MIN (0)
#define CANSIG_DIM_FAULTS_DIM_MISSING_HEARTBEAT_FAULT_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_WATCHDOG_TIMEOUT_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_WATCHDOG_TIMEOUT_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_TX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_TX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_DCM_WARNINGS_DCM_RX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_DCM_WARNINGS_DCM_RX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_DCM_FAULTS_DCM_MISSING_HEARTBEAT_FAULT_MIN (0)
#define CANSIG_DCM_FAULTS_DCM_MISSING_HEARTBEAT_FAULT_MAX (1)
#define CANSIG_DCM_FAULTS_DCM_LEFT_INVERTER_FAULT_MIN (0)
#define CANSIG_DCM_FAULTS_DCM_LEFT_INVERTER_FAULT_MAX (1)
#define CANSIG_DCM_FAULTS_DCM_RIGHT_INVERTER_FAULT_MIN (0)
#define CANSIG_DCM_FAULTS_DCM_RIGHT_INVERTER_FAULT_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_WATCHDOG_TIMEOUT_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_WATCHDOG_TIMEOUT_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_TX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_TX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_BMS_WARNINGS_BMS_RX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_BMS_WARNINGS_BMS_RX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_MISSING_HEARTBEAT_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_MISSING_HEARTBEAT_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_STATE_MACHINE_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_STATE_MACHINE_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERVOLTAGE_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERVOLTAGE_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERVOLTAGE_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERVOLTAGE_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_MODULE_COMMUNICATION_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_MODULE_COMMUNICATION_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERTEMP_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_UNDERTEMP_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERTEMP_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CELL_OVERTEMP_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_DISCONNECTED_DURING_CHARGE_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_DISCONNECTED_DURING_CHARGE_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_EXTERNAL_SHUTDOWN_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_CHARGER_EXTERNAL_SHUTDOWN_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_TRACTIVE_SYSTEM_OVERCURRENT_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_TRACTIVE_SYSTEM_OVERCURRENT_FAULT_MAX (1)
#define CANSIG_BMS_FAULTS_BMS_PRECHARGE_FAILURE_FAULT_MIN (0)
#define CANSIG_BMS_FAULTS_BMS_PRECHARGE_FAILURE_FAULT_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_WATCHDOG_TIMEOUT_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_WATCHDOG_TIMEOUT_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_TX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_TX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_PDM_WARNINGS_PDM_RX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_PDM_WARNINGS_PDM_RX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_PDM_FAULTS_PDM_DUMMY_FAULT_MIN (0)
#define CANSIG_PDM_FAULTS_PDM_DUMMY_FAULT_MAX (1)
#define CANSIG_DEBUG_CAN_MODE_DEBUG_ENABLE_DEBUG_MODE_MIN (0)
#define CANSIG_DEBUG_CAN_MODE_DEBUG_ENABLE_DEBUG_MODE_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1_HZ_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK100_HZ_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK1K_HZ_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_RX_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STACK_WATER_MARK_HIGH_TASK_CAN_TX_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_WATCHDOG_TIMEOUT_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_WATCHDOG_TIMEOUT_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_TX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_TX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_RX_OVERFLOW_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_RX_OVERFLOW_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_LEFT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_LEFT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_RIGHT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_RIGHT_WHEEL_SPEED_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OCSC_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OCSC_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_STEERING_ANGLE_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_FRONT_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_FRONT_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_REAR_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_REAR_BRAKE_PRESSURE_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_FLOW_RATE_OUT_OF_RANGE_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_FLOW_RATE_OUT_OF_RANGE_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_BRAKE_APPS_DISAGREEMENT_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_BRAKE_APPS_DISAGREEMENT_WARNING_MAX (1)
#define CANSIG_FSM_WARNINGS_FSM_APPS_DISAGREEMENT_WARNING_MIN (0)
#define CANSIG_FSM_WARNINGS_FSM_APPS_DISAGREEMENT_WARNING_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_MISSING_HEARTBEAT_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_MISSING_HEARTBEAT_FAULT_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_STATE_MACHINE_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_STATE_MACHINE_FAULT_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_PAPPS_OCSC_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_PAPPS_OCSC_FAULT_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_SAPPS_OCSC_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_SAPPS_OCSC_FAULT_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_FLOW_METER_UNDERFLOW_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_FLOW_METER_UNDERFLOW_FAULT_MAX (1)
#define CANSIG_FSM_FAULTS_FSM_TORQUE_PLAUSABILITY_FAILED_FAULT_MIN (0)
#define CANSIG_FSM_FAULTS_FSM_TORQUE_PLAUSABILITY_FAILED_FAULT_MAX (1)


/* -------------------------------- Enums --------------------------------- */

typedef enum
{
    SWITCH_OFF = 0,
    SWITCH_ON = 1,
    NUM_SWITCH_STATE_CHOICES = 2,
} SwitchState;

typedef enum
{
    RTOS_TASK_1HZ = 0,
    RTOS_TASK_100HZ = 1,
    RTOS_TASK_1KHZ = 2,
    RTOS_TASK_CAN_TX = 3,
    RTOS_TASK_CAN_RX = 4,
    NUM_RTOS_TASK_NAME_CHOICES = 5,
} RtosTaskName;

typedef enum
{
    INVERTER_VSM_START_STATE = 0,
    INVERTER_VSM_PRECHARGE_INIT_STATE = 1,
    INVERTER_VSM_PRECHARGE_ACTIVE_STATE = 2,
    INVERTER_VSM_PRECHARGE_COMPLETE_STATE = 3,
    INVERTER_VSM_WAIT_STATE = 4,
    INVERTER_VSM_READY_STATE = 5,
    INVERTER_VSM_MOTOR_RUNNING_STATE = 6,
    INVERTER_VSM_BLINK_FAULT_CODE_STATE = 7,
    INVERTER_VSM_SHUTDOWN_IN_PROCESS = 14,
    INVERTER_VSM_RECYCLE_POWER_STATE = 15,
    NUM_INVERTER_VSM_STATE_CHOICES = 10,
} InverterVsmState;

typedef enum
{
    INVERTER_POWER_ON_STATE = 0,
    INVERTER_STOP_STATE = 1,
    INVERTER_OPEN_LOOP_STATE = 2,
    INVERTER_CLOSED_LOOP_STATE = 3,
    INVERTER_WAIT_STATE = 4,
    INVERTER_IDLE_RUN_STATE = 8,
    INVERTER_IDLE_STOP_STATE = 9,
    NUM_INVERTER_STATE_CHOICES = 7,
} InverterState;

typedef enum
{
    INVERTER_ACTIVE_DISCHARGE_DISABLED = 0,
    INVERTER_ACTIVE_DISCHARGE_ENABLED_WAITING = 1,
    INVERTER_ACTIVE_DISCHARGE_PERFORMING_SPEED_CHECK = 2,
    INVERTER_ACTIVE_DISCHARGE_OCCURING = 3,
    INVERTER_ACTIVE_DISCHARGE_COMPLETED = 4,
    NUM_INVERTER_ACTIVE_DISCHARGE_STATE_CHOICES = 5,
} InverterActiveDischargeState;

typedef enum
{
    INVERTER_CAN_MODE = 0,
    INVERTER_VSM_MODE = 1,
    NUM_INVERTER_COMMAND_MODE_CHOICES = 2,
} InverterCommandMode;

typedef enum
{
    INVERTER_LOCKOUT_UNLOCKED = 0,
    INVERTER_LOCKOUT_LOCKED = 1,
    NUM_INVERTER_LOCKOUT_CHOICES = 2,
} InverterLockout;

typedef enum
{
    INVERTER_REVERSE_DIRECTION = 0,
    INVERTER_FORWARD_DIRECTION = 1,
    NUM_INVERTER_DIRECTION_CHOICES = 2,
} InverterDirection;

typedef enum
{
    INVERTER_READ_COMMAND = 0,
    INVERTER_WRITE_COMMAND = 1,
    NUM_INVERTER_READ_WRITE_COMMAND_CHOICES = 2,
} InverterReadWriteCommand;

typedef enum
{
    RANGE_CHECK_OK = 0,
    RANGE_CHECK_UNDERFLOW = 1,
    RANGE_CHECK_OVERFLOW = 2,
    NUM_RANGE_CHECK_CHOICES = 3,
} RangeCheck;


/* ------------------------------- Structs -------------------------------- */

/**
 * Signals in CAN msg GSM_GSM_Vitals.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool GSM_Heartbeat_value;
} GSM_GSM_Vitals_Signals;

/**
 * Signals in CAN msg GSM_GSM_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool GSM_StackWatermarkAboveThresholdTask1Hz_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_StackWatermarkAboveThresholdTask100Hz_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_StackWatermarkAboveThresholdTask1kHz_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_StackWatermarkAboveThresholdTaskCanTx_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_StackWatermarkAboveThresholdTaskCanRx_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_WatchdogTimeout_value;
    /**
     * Range: 0 to 255
     */
    uint32_t GSM_TxOverflowCount_value;
    /**
     * Range: 0 to 255
     */
    uint32_t GSM_RxOverflowCount_value;
    /**
     * Range: 0 to 4
     */
    RtosTaskName GSM_WatchdogTimeoutTaskName_value;
} GSM_GSM_Warnings_Signals;

/**
 * Signals in CAN msg GSM_StackRemaining.
 */
typedef struct
{
    /**
     * Range: 0% to 100%
     */
    uint32_t GSM_StackRemainingTask1Hz_value;
    /**
     * Range: 0% to 100%
     */
    uint32_t GSM_StackRemainingTask100Hz_value;
    /**
     * Range: 0% to 100%
     */
    uint32_t GSM_StackRemainingTask1kHz_value;
    /**
     * Range: 0% to 100%
     */
    uint32_t GSM_StackRemainingTaskCanRx_value;
    /**
     * Range: 0% to 100%
     */
    uint32_t GSM_StackRemainingTaskCanTx_value;
} GSM_StackRemaining_Signals;

/**
 * Signals in CAN msg GSM_CommitInfo.
 */
typedef struct
{
    /**
     * Range: 0 to 4294967295
     */
    uint32_t GSM_Hash_value;
    /**
     * Range: 0 to 1
     */
    bool GSM_Clean_value;
} GSM_CommitInfo_Signals;

/**
 * Signals in CAN msg DIM_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool DIM_StackWaterMarkHighTask1HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_StackWaterMarkHighTask100HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_StackWaterMarkHighTask1kHzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_StackWaterMarkHighTaskCanRxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_StackWaterMarkHighTaskCanTxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_WatchdogTimeoutWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_TxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DIM_RxOverflowWarning_value;
} DIM_Warnings_Signals;

/**
 * Signals in CAN msg DIM_Faults.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool DIM_MissingHeartbeatFault_value;
} DIM_Faults_Signals;

/**
 * Signals in CAN msg DCM_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool DCM_StackWaterMarkHighTask1HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_StackWaterMarkHighTask100HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_StackWaterMarkHighTask1kHzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_StackWaterMarkHighTaskCanRxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_StackWaterMarkHighTaskCanTxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_WatchdogTimeoutWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_TxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_RxOverflowWarning_value;
} DCM_Warnings_Signals;

/**
 * Signals in CAN msg DCM_Faults.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool DCM_MissingHeartbeatFault_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_LeftInverterFault_value;
    /**
     * Range: 0 to 1
     */
    bool DCM_RightInverterFault_value;
} DCM_Faults_Signals;

/**
 * Signals in CAN msg BMS_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool BMS_StackWaterMarkHighTask1HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_StackWaterMarkHighTask100HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_StackWaterMarkHighTask1kHzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_StackWaterMarkHighTaskCanRxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_StackWaterMarkHighTaskCanTxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_WatchdogTimeoutWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_TxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_RxOverflowWarning_value;
} BMS_Warnings_Signals;

/**
 * Signals in CAN msg BMS_Faults.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool BMS_MissingHeartbeatFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_StateMachineFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_CellUndervoltageFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_CellOvervoltageFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_ModuleCommunicationFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_CellUndertempFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_CellOvertempFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_ChargerFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_ChargerDisconnectedDuringChargeFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_ChargerExternalShutdownFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_TractiveSystemOvercurrentFault_value;
    /**
     * Range: 0 to 1
     */
    bool BMS_PrechargeFailureFault_value;
} BMS_Faults_Signals;

/**
 * Signals in CAN msg PDM_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool PDM_StackWaterMarkHighTask1HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_StackWaterMarkHighTask100HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_StackWaterMarkHighTask1kHzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_StackWaterMarkHighTaskCanRxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_StackWaterMarkHighTaskCanTxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_WatchdogTimeoutWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_TxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool PDM_RxOverflowWarning_value;
} PDM_Warnings_Signals;

/**
 * Signals in CAN msg PDM_Faults.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool PDM_DummyFault_value;
} PDM_Faults_Signals;

/**
 * Signals in CAN msg Debug_CanMode.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool Debug_EnableDebugMode_value;
} Debug_CanMode_Signals;

/**
 * Signals in CAN msg FSM_Warnings.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool FSM_StackWaterMarkHighTask1HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_StackWaterMarkHighTask100HzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_StackWaterMarkHighTask1kHzWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_StackWaterMarkHighTaskCanRxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_StackWaterMarkHighTaskCanTxWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_WatchdogTimeoutWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_TxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_RxOverflowWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_LeftWheelSpeedOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_RightWheelSpeedOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_SteeringAngleOCSCWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_SteeringAngleOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_FrontBrakePressureOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_RearBrakePressureOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_FlowRateOutOfRangeWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_BrakeAppsDisagreementWarning_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_AppsDisagreementWarning_value;
} FSM_Warnings_Signals;

/**
 * Signals in CAN msg FSM_Faults.
 */
typedef struct
{
    /**
     * Range: 0 to 1
     */
    bool FSM_MissingHeartbeatFault_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_StateMachineFault_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_PappsOCSCFault_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_SappsOCSCFault_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_FlowMeterUnderflowFault_value;
    /**
     * Range: 0 to 1
     */
    bool FSM_TorquePlausabilityFailedFault_value;
} FSM_Faults_Signals;


/* ------------------------- Function Prototypes -------------------------- */

/**
 * Pack signals into CAN payload for GSM_GSM_Vitals.
 */
void App_CanUtils_GSM_GSM_Vitals_Pack(const GSM_GSM_Vitals_Signals* const in_msg, uint8_t* const out_data);

/**
 * Pack signals into CAN payload for GSM_GSM_Warnings.
 */
void App_CanUtils_GSM_GSM_Warnings_Pack(const GSM_GSM_Warnings_Signals* const in_msg, uint8_t* const out_data);

/**
 * Pack signals into CAN payload for GSM_StackRemaining.
 */
void App_CanUtils_GSM_StackRemaining_Pack(const GSM_StackRemaining_Signals* const in_msg, uint8_t* const out_data);

/**
 * Pack signals into CAN payload for GSM_CommitInfo.
 */
void App_CanUtils_GSM_CommitInfo_Pack(const GSM_CommitInfo_Signals* const in_msg, uint8_t* const out_data);

/**
 * Unpack signals from CAN payload for DIM_Warnings.
 */
void App_CanUtils_DIM_Warnings_Unpack(const uint8_t* const in_data, DIM_Warnings_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for DIM_Faults.
 */
void App_CanUtils_DIM_Faults_Unpack(const uint8_t* const in_data, DIM_Faults_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for DCM_Warnings.
 */
void App_CanUtils_DCM_Warnings_Unpack(const uint8_t* const in_data, DCM_Warnings_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for DCM_Faults.
 */
void App_CanUtils_DCM_Faults_Unpack(const uint8_t* const in_data, DCM_Faults_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for BMS_Warnings.
 */
void App_CanUtils_BMS_Warnings_Unpack(const uint8_t* const in_data, BMS_Warnings_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for BMS_Faults.
 */
void App_CanUtils_BMS_Faults_Unpack(const uint8_t* const in_data, BMS_Faults_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for PDM_Warnings.
 */
void App_CanUtils_PDM_Warnings_Unpack(const uint8_t* const in_data, PDM_Warnings_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for PDM_Faults.
 */
void App_CanUtils_PDM_Faults_Unpack(const uint8_t* const in_data, PDM_Faults_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for Debug_CanMode.
 */
void App_CanUtils_Debug_CanMode_Unpack(const uint8_t* const in_data, Debug_CanMode_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for FSM_Warnings.
 */
void App_CanUtils_FSM_Warnings_Unpack(const uint8_t* const in_data, FSM_Warnings_Signals* const out_msg);

/**
 * Unpack signals from CAN payload for FSM_Faults.
 */
void App_CanUtils_FSM_Faults_Unpack(const uint8_t* const in_data, FSM_Faults_Signals* const out_msg);

