version: '3.9'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    env_file:
      - /Users/matthe/CodingProjects/Consolidated-Firmware/software/tracksight/live_data/influx.env

volumes:
  influxdb-data: