#pragma once

typedef enum
{
    BMS_HEARTBEAT_BOARD,
    VC_HEARTBEAT_BOARD,
    RSM_HEARTBEAT_BOARD,
    FSM_HEARTBEAT_BOARD,
    DIM_HEARTBEAT_BOARD,
    CRIT_HEARTBEAT_BOARD,
    HEARTBEAT_BOARD_COUNT
} HeartbeatBoards;
