# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_modules.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug_modules.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x64\x65\x62ug_modules.proto\"\"\n\x04Gpio\x12\x0b\n\x03pin\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x08\"\x1b\n\nAdcChannel\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3'
)




_GPIO = _descriptor.Descriptor(
  name='Gpio',
  full_name='Gpio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='Gpio.pin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Gpio.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=57,
)


_ADCCHANNEL = _descriptor.Descriptor(
  name='AdcChannel',
  full_name='AdcChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='AdcChannel.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Gpio'] = _GPIO
DESCRIPTOR.message_types_by_name['AdcChannel'] = _ADCCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gpio = _reflection.GeneratedProtocolMessageType('Gpio', (_message.Message,), {
  'DESCRIPTOR' : _GPIO,
  '__module__' : 'debug_modules_pb2'
  # @@protoc_insertion_point(class_scope:Gpio)
  })
_sym_db.RegisterMessage(Gpio)

AdcChannel = _reflection.GeneratedProtocolMessageType('AdcChannel', (_message.Message,), {
  'DESCRIPTOR' : _ADCCHANNEL,
  '__module__' : 'debug_modules_pb2'
  # @@protoc_insertion_point(class_scope:AdcChannel)
  })
_sym_db.RegisterMessage(AdcChannel)


# @@protoc_insertion_point(module_scope)
