name: UBC Formula Electric CI
on:
  push:
    branches:
      - master
      - faster-ci
  pull_request:
    branches:
      - master

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv==2021.11.5

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          cache: pipenv
          cache-dependency-path: Pipfile.lock
        
      - name: Install dependencies
        run: pipenv install
      
      - name: Format code
        run: python clang-format/fix_formatting.py

      - name: Check for differences
        run: git --no-pager diff --color

  codegen:
    name: Check STM32CubeMX Code Generation
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        board:
          - FSM
          - PDM
          - BMS
          - DCM
          - DIM
    env:
      INSTALL_DIR: /usr/local
      CUBE_INSTALL_DIR: $INSTALL_DIR/STM32CubeMX
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Install pipenv
        run: pip install pipenv==2021.11.5

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          cache: pipenv
          cache-dependency-path: Pipfile.lock

      - name: Install dependencies
        run: pipenv install

      - name: Install XVFB
        run: |
          sudo apt-get install xvfb
          sudo cp ./scripts/environment_setup/xvfb.service /etc/systemd/system/xvfb.service
          sudo systemctl start xvfb

      - name: Setup STM32CubeMx install cache
        uses: actions/cache@v2
        with:
          path: /usr/local/STM32CubeMX
          key: ${{ hashFiles('./tools/en.STM32CubeMX*.zip') }}

      - name: Install STM32CubeMX
        run: pipenv run python scripts/environment_setup/install_cube.py /usr/local/STM32CubeMX ./tools/en.STM32CubeMX_v5-3-0.zip
        if: hashFiles('/usr/local/STM32CubeMX/STM32CubeMX') == '' # Rudimentary check if install was cached

      - name: Generate code
        env:
          DISPLAY: :99.0
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD
          python scripts/utilities/generate_cube_code.py \
            --board ${{ matrix.board }} \
            --log4j_properties_output ~/.stm32cubemx/log4j.properties \
            --ioc boards/${{ matrix.board }}/${{ matrix.board }}.ioc \
            --codegen_output_dir boards/${{ matrix.board }} \
            --cube_bin $CUBE_INSTALL_DIR/STM32CubeMX
          python clang-format/fix_formatting.py
      
      - name: Check for differences
        run: git --no-pager diff --color
