name: Tracksight Backend CI
run-name: Tracksight Backend CI 🚀
on:
  push:
    paths:
      #- "software/tracksight/backend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: software/tracksight/backend/environment.yml
          activate-environment: tracksight-backend

      - name: List Conda Envs
        run: |
          conda env list
      - name: Build and test
        run: |
          conda activate tracksight-backend

      - name: Deactivate Conda environment
        run: conda deactivate

