name: Tracksight Backend CI 
run-name: Tracksight Backend CI 🚀
on:
  push:
    paths:
      - "software/tracksight/backend/**"
jobs:
  build:
    runs-on: ubcformulaelectric/environment:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Start Flask app
        run: |
          cd software/tracksight/backend
          python3 app/telemetry.py & sleep 10
          curl --fail http://localhost:5000
        env:
          FLASK_ENV: development

      - name: Kill Flask process
        if: always()
        run: kill $(jobs -p) || true

            
